### ISSUE TITLE
Palindrome Product Exercise (es6)

### ISSUE THREAD

**Issue by wilmoore** [exercism/javascript#1]
## Todos
- [x] Build a sane test workflow.
- [x] Clean up exercise.

**Comment by rchavarria** [comment]
Hi,
Sorry if this is not the right place, but I'm not sure where to ask.
How could I run my production code against the tests provided by exercism?
I've tried to run them with the command under the `ecmascript/palindrome-products` folder:

    jasmine-node .

But I get this error:

    C:\Users\rchavarria\exercism\ecmascript\palindrome-products\palindrome-products.js:7
    function generate({ minFactor = 1, maxFactor = Number.MAX_VALUE }) {
                      ^
    Exception loading: C:\Users\rchavarria\exercism\ecmascript\palindrome-products\palindrome-products_test.spec.js
    [SyntaxError: Unexpected token {]

It seems the ECMAScript 6 code is not transpiled to ECMAScript 5 before running the tests, but I don't know how to tell traceour to do it.

Thanks in advance.

**Comment by kytrinyx** [comment]
@rchavarria You'll probably get more help asking in the support channel: https://gitter.im/exercism/support -- if not, you might also be able to get some help on StackOverflow (not the exercism-specific part, but there are a lot of knowledgable people who, if you tell them what the filenames and paths and bits of code are, could probably give you an answer quickly.

**Comment by rchavarria** [comment]
Ok, thanks. I'll try first the support channel.
