### ISSUE TITLE
CI should check if repository value of package.json is sane

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#1013]
Related #1007.

## Description

We have two scripts that check the integrity of the repository files, or pr changed files respectively: [`scripts/ci-check`] and [`scripts/pr-check`](https://github.com/exercism/javascript/blob/main/scripts/pr-check).

These are their steps:

1. check if stub file exists
2. check if their configuration files have the right _integrity_ (check if the files in `exercises/*/*/` match those of the root, because we want the same `eslint`, `babel`, etc. configuration for all exercises).
3. check if the files pass the linter (`eslint`).

## Current behaviour

The integrity step correctly removes some fields from `package.json` before comparing the root file with the exercise file. However, this makes it possible to have a exercise `package.json` with incorrect values for the `repository` key.

Currently, the `repository` key's value is completely ignored.

## Expected behaviour

Instead, the `package.json` in the exercise directory should:

1. match `type` of the root `package.json` `repository`
2. match `url` of the root `package.json` `repository`
3. have the correct `directory` based on the path to the exercise

**Comment by AbhilashJN** [comment]
I can work on this one.
