### ISSUE TITLE
Improve Concept Exercise: Numbers (Freelancer Rates)

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1049]
## Getting started
Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

If you have not done so yet, it is probably also helpful to do a couple of "Learning Exercises" (this is how they are called on the site) yourself.

## Goal

The goal of this issue is to extend the existing concept exercise [Freelancer Rates](https://github.com/exercism/javascript/tree/main/exercises/concept/freelancer-rates) that teaches the `numbers` concept.

The exercise is already in good shape but currently only explicitly introduces numbers as a concept. **Additionally it should also introduce arithmetic operators incl. shorthand assignment operators.**

See [this list](https://github.com/exercism/javascript/issues/951#issuecomment-778834953) for details on the learning curve we are aiming for.

## Additional Learning Objectives
- How to do perform the following 6 arithmetic operations: addition, subtraction, multiplication, division, remainder, exponentiation
- What are shorthand assignment operators for those 6 operations and how to use them

(To avoid too many tiny concepts, both of these will be combined in one additional concept called `arithmetic-operators`.)

### Add Concept
- [x] Create a new folder  `arithmetic-operators` in `concepts` and add the concept to the general config.json file (incl. adding it to `concepts` for the `freelancer-rates` exercise there)
- [x] Write the introduction.md, about.md and links.json file for the concept

### Adjust the Concept Exercise
- [x] Add the introduction.md of the concept at the end of the introduction.md file of the exercise, make some adjustments in the content if necessary.
- [x] Adjust the design.md file to incorporate the new learning objectives.
- [x] Update the tasks in the exercise to include at least one use of one of the more unusual operators (`%` or `**`) and one sensible use of a shorthand assignment operator. You can add new additional tasks but you can also consider replacing/adjusting an existing task that might currently not teach much more than the other tasks already do. Updating the tasks includes the following files
  - instructions.md
  - hints.md
  - exemplar.js
  - stub file (freelancer-rates.js)
  - test file (freelancer-rates.spec.js)

### Fixes for the Existing Content
This part is optional polishing "while you are at it" but can also be tackled in another issue/PR later.

- [x] Fix broken link in "Built-in Object" section
- [ ] About.md for numbers could benefit from the following additions:
  - explain the 3 special numbers: NaN and +/- Infinity
  - show how to write numbers with underscore or exponential notation
- [x] Remove the section on comparison, it is now included in the comparison concept, instead just keep the link ("How to compare numbers is explained in ...")
- [x] The current exercise requires rounding to solve it. The introduction.md of the exercise currently does not include this. It should point the students to a list of the rounding methods, e.g. like [this one](https://javascript.info/number#rounding), so they don't get lost reading about rounding in JavaScript. Also update the introduction.md of the numbers concept to keep them roughly in sync.
- [x] See comments below for other issues that students found that should be addressed.

## Ideas for About.md of the New Concept
- `/` does not perform integer division like in some other languages
- behavior of `%` if one operand is negative, see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder) below the demo box
- typical use of `%` for keeping a value inside a range/ "if you reach the end while iterating, start from the beginning" (not sure how to describe this well but explanation should also be understandable for someone who does not know ring theory)
- `**` does the same as the older `Math.pow()`

## Help

You can choose to do this solo-style, or collaborate with multiple people on this. The suggested approach is to

1. **First accept this issue by saying "I'd like to work on this"** (no need to wait for a response, just go with it) and optionally request that someone works with you (and wait for a second person to accept your request).
2. Use this issue to discuss any questions you have, what should be included in the content and what not and to collect reference material.
3. Create a PR and set "exercism/javascript" as reviewers. Additionally you can write in #maintaining-javascript that your PR is ready for review. Once you incorporated any critical feedback that the reviewer might give you and the PR is approved, it will be merged by a maintainer.

## Credit
This contribution grants you an _author_ slot. Add your username to the **`authors`** key in the [config file](https://github.com/exercism/javascript/blob/main/exercises/concept/freelancer-rates/.meta/config.json).

**Comment by junedev** [comment]
@NobbZ did this exercise and noted two things.
* There is a `applyDiscount` stub provided which you don't really need to use. If you don't use it, it looks like there is a `throw new Error(...)` left even though everything is fine and all tests pass. Since "use helper functions" is not the main focus for this early  exercise, it is probably best to remove that stub.
* Task 2 states to round up the result but this is easily overlooked. Maybe make that part a separate sentence so it is more prominent.

**Comment by benallan** [comment]
Hi, I just did this exercise and found one part a bit unclear:
> If the freelancer bills the project manager per month, there is a discount applied

I assumed this meant that each full month gets a discount, and any leftover days are billed at the full day rate. But from the expected results in the tests it seems that the discount needs to be applied to all days regardless of whether they make up a full month. 

(Apologies if this was clear to everyone else!)

**Comment by junedev** [comment]
@benallan Good point! We should clarify that in the instructions.

**Comment by junedev** [comment]
Another comment by a student that was confused:

> Looking at all the community solutions, I've seen the Math.ceil() function applied directly to the applyDiscount() function. However, this function is being used by both the monthRate() and the daysInBudget() functions. Additionally, it seems like the instructions wants me to treat both values from the aforementioned functions differently.

**Comment by JaPatGitHub** [comment]
I'd like to work on this

**Comment by junedev** [comment]
@JaPatGitHub There are a lot of todos here. Feel free to only tackle some of them first. Your PR does not have to include all things at once. Also if you don't feel like doing all the parts we can put the rest in some new issue later.

**Comment by JaPatGitHub** [comment]
Hello @junedev, my pleasure to work on this!
Where do I find the About.md file you mentioned under **Fixes for Existing Content** of this issue?
Did you mean introduction.md?

**Comment by junedev** [comment]
Please make sure you have read the documentation listed under "Getting started" above. There you learn that there are the concepts (in this `numbers`) and concept exercises (`freelancer-rates`), they exist in different root level folders. About.md is part of the numbers concept: https://github.com/exercism/javascript/blob/main/concepts/numbers/about.md

**Comment by JaPatGitHub** [comment]
I have two questions now:
i) What do I do for the uuid of arithmetic-operators in the general config.json file?
ii) Should I create a .meta/config.json file under arithmetic-operators folder? (I see it's there in all other concept folders but it's not mentioned in the tasks of this issue)

**Comment by junedev** [comment]
You can use configlet to generate the uuid: https://github.com/exercism/configlet#configlet-uuid

How to fetch configlet is documented here: https://github.com/exercism/javascript/blob/main/CONTRIBUTING.md#fetch-configlet

**Comment by JaPatGitHub** [comment]
Thank you @junedev. Went through the links you sent and tried implementing. I don't exactly get how to run the [`fetch-configlet`](https://github.com/exercism/javascript/blob/main/bin/fetch-configlet) binary on my windows computer (I've downloaded my fork of the repository locally). How do I do that?

 Not much great help on google searches

**Comment by SleeplessByte** [comment]
@JaPatGitHub if you're on windows, open PowerShell and `cd` to the `javascript` folder. Then run <https://github.com/exercism/javascript/blob/main/bin/fetch-configlet.ps1> instead like this:

```powershell
bin/fetch-configlet.ps1
```

If you're not on windows, `cd` to the `javascript` folder, then run <https://github.com/exercism/javascript/blob/main/bin/fetch-configlet> like this:

```shell
bin/fetch-configlet
```

Both will result in `configlet` or `configlet.exe` to be placed in that `bin` folder.

**Comment by Fbrufino** [comment]
> Hi, I just did this exercise and found one part a bit unclear:
> 
> > If the freelancer bills the project manager per month, there is a discount applied
> 
> I assumed this meant that each full month gets a discount, and any leftover days are billed at the full day rate. But from the expected results in the tests it seems that the discount needs to be applied to all days regardless of whether they make up a full month.
> 
> (Apologies if this was clear to everyone else!)


That wasn't my exact thought process, but I also was confused at task 3 as to which rate I was supposed to use, and even though I could guess from the function inputs and also the clue that
> _"If the freelancer bills the project manager per month, there is a discount applied. **This can be handy if the project manager has a fixed budget**",_

I thought it was more vague than it should. In the end, it seems the whole monthly rate could actually be dispensed with in favor of talking directly in terms of something like a single-charge rate or a fixed-budget rate. That would make things clearer.

Also, I've just checked the hint for this task before commenting here, and I think it can even add to the confusion by mentioning `dayRate`, i.e., the _other_ function. It seems to be suggesting the user to use that instead of `monthRate`. I think it can be improved just by making the following change:

| old | new |
| --- | --- |
| "First determine the dayRate, given the discount" | "First determine the day rate given the discount" |

**Comment by JaPatGitHub** [comment]
@Fbrufino, I agree with you. I got your second point about changing `dayRate` to 'day rate' in the hint.
But I don't exactly get your first point - why do you think it's vague? What changes do you recommend?

**Comment by junedev** [comment]
I agree with @Fbrufino but I would even go further than the changes he suggested

* Use task 3 as task 2 and completely remove the discount from that task. It is fine if that task is just about doing division and using Math.floor.
* As for the descriptions, I would recommend removing this part from the "introduction" section entirely.
    ```
    We first establish a few rules between the freelancer and the project manager:

    - The daily rate is 8 times the hourly rate;
    - A month has 22 billable days.

    If the freelancer bills the project manager per month or more, there is a discount applied. This can be handy if the project manager has a fixed budget.

    Discounts are modeled as fractional numbers (percentage) between `0.0` (`0%`, no discount) and `0.90` (`90%`, maximum discount).
    ```
    Instead present that information in the task where it is needed.
    So each task has a short "story" part and then the `Implement ...` section. For example
    ```
    ## 1. Calculate the day rate given an hourly rate
    The freelancer contract defines that the daily rate is 8 times the hourly rate.
    
    Implement ...
    ```

With these two changes there is no confusion anymore which information needs to be applied in which task. `applyDiscount` is not reused (and should be removed in any case) so there is also no confusion whether to apply the rounding there or not. Only the new task 3 would mention the discount.

**Comment by JaPatGitHub** [comment]
@junedev 
**Regarding Test Files** 
Thank you! I find these instructions comprehensive enough to start working. Will mention here if I face any difficulties :)

**Regarding Remainder Operator**
I think we had a miscommunication - my idea was meant for the new task 3 (not 2 - it stays clear of discount calculation)

However, I find your story good too. So which one do you think should we work on?

**Comment by JaPatGitHub** [comment]
@junedev, I wish to add everyone who gave suggestions in this issue in the `.meta/config.json` contributor list.
Are you okay with that?

**Comment by junedev** [comment]
@JaPatGitHub That is very nice of you but the contributor slot is meant for the person that actually did the change in the code and that means you. 🙂

**Comment by JaPatGitHub** [comment]
I've been thinking about the use of shorthand arithmetic operators in the exercise. Do you think we can make sensible use of it in this exercise? In my experience, I've mainly used shorthand operators only in loops - beyond the scope of this exercise.

**Comment by junedev** [comment]
@JaPatGitHub Good point, I asked myself the same. I couldn't think of a good exercise here and there are a couple of other exercises later where these operators are used and the analyzer can tell students if they didn't use them there. So that's good enough for now.

**Comment by junedev** [comment]
@JaPatGitHub All the main points from this issue are addressed now. :tada: Thanks again! The only thing left are some improvements for the about.md file. Do you want to work on those as well? If not, I would move them to a new issue and consider this one closed.

**Comment by JaPatGitHub** [comment]
@junedev, I'm glad to have worked on this. This was my first open-source contribution apart from fixing typos and broken links. A personal thank you for your reviews - made me go a long way!

I plan to stay dormant on GitHub for the rest of this month as I have my exams and the courseload is heavy. Hence I think it would be better to move to a new issue so that someone else can work on it or I tackle it later :-)

**Comment by junedev** [comment]
The ticket with the leftover items is here: https://github.com/exercism/javascript/issues/1505
