### ISSUE TITLE
Check corejs version in babel configuration versus package.json

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#1182]
[`core-js`](https://github.com/zloirock/core-js#babel) is configured in our `babel.config.js` / `.babelrc`. It's version in our dependency list in `package.json` (currently `3.14.x`) must match the babel setting without the patch version. 

In other words, given a `package.json` version of `3.14.x`, the configuration setting must be `3.14`.

Your task, should you accept it, is to add a check to the "precheck" scripts that run automatically on PR requests is to check if the package.json version matches the babel configuration version, up to the minor (major.minor.patch) version.

**Comment by ffflorian** [comment]
I'd like to take over this task :slightly_smiling_face:

**Comment by junedev** [comment]
@ffflorian You don't need to check all package.json and babel.config.js files, you only need to check those in the root directory. They are then synced from there to all the exercises via another script, so if they are correct in the root directory, they will be correct everywhere (or CI will complain about it).

**Comment by ffflorian** [comment]
[Done](https://github.com/exercism/javascript/pull/1313) :slightly_smiling_face:
