### ISSUE TITLE
Fix wording in concept exercise stub ("method" -> "function")

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1298]
There are some concept exercises where the error message in the stub says "implement the method" but what people should implement is just a function, not a method.

So for example
```javascript
export function preparationTimeInMinutes(numberOfLayers) {
  throw new Error('Please implement the preparationTimeInMinutes method');
}
```
should be changed to
```javascript
export function preparationTimeInMinutes(numberOfLayers) {
  throw new Error('Please implement the preparationTimeInMinutes function');
}
```

This needs to fixed in the stub files of the following exercises.
* `bird-watcher`
* `lasagna`
* `ozans-playlist`
* `vehicle-purchase`

Leave a comment below, when you want to work on this.

**Comment by SleeplessByte** [comment]
Yesss. Very nicely spotted.

**Comment by MukulKolpe** [comment]
Hey @junedev can I work on this issue?

**Comment by junedev** [comment]
Of course, go ahead!
