### ISSUE TITLE
high-score-board: package-lock.json is commited

### ISSUE THREAD

**Issue by NobbZ** [exercism/javascript#1307]
Hi there, it seems as if for `high-score-board` the `package-lock.json` got comitted into the repository.

This is the first exercise containing it among those I did, and I haven't found it in any of the other 3 random picks I did in this repository.

I realized it, as `yarn` warned me about it.

**Comment by junedev** [comment]
Thanks for reporting this!

**Comment by NobbZ** [comment]
Then I'll take the issue happily!

**Comment by emanual4real** [comment]
We regularly commit package-lock.json for npm.  Is it different with yarn?

**Comment by junedev** [comment]
@NobbZ 😆 I was rather thinking of some newcomer picking this up.

**Comment by junedev** [comment]
@emanual4real With both npm and yarn, you usually commit the lock file. Have a look at the discussion in #703 I mentioned for details on the challenges with that in the exercise context.

**Comment by NobbZ** [comment]
> @NobbZ  I was rather thinking of some newcomer picking this up.

Oh… Haven't seen the label. I will then also happily remove the PR and again.

**Comment by junedev** [comment]
Well, of course we can merge it when you already did the work now. 🙂
