### ISSUE TITLE
Wrong value in unit tests for high-score-board

### ISSUE THREAD

**Issue by slavict** [exercism/javascript#1317]
Wrong value passed to updateScore function in unit tests for high-score-board at https://exercism.org/tracks/javascript/exercises/high-score-board exercise
![image](https://user-images.githubusercontent.com/16884974/132247458-03ca9dda-fc4c-4961-b168-97bdf4c56f35.png)

**Comment by slavict** [comment]
It's seems that I didn't understand instruction. Sorry my bad.

**Comment by junedev** [comment]
If you have an idea how to improve the instructions please let us know.
