### ISSUE TITLE
Improve Concept Exercise: Elyses Transformative Enchantments (array-transformations)

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1326]
The goal of this task is to make sure the Concept Exercise "Elyses Transformative Enchantments" conform to the latest specification. As part of that, the concept `array-transformations` has to be created.

The docs can be found here
- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

Additionally you can look at the `bird-watcher` concept exercise for reference.

The improvement should include changing the introduction.md file of the exercise to contain some minimal information so that the student is able to solve the exercise. For now it is ok to use that same content as introduction.md and about.md for the Concept as well.

Also ensure that
* there are good blurbs for the concept and exercise
* the tests are declarative (see https://github.com/exercism/javascript/issues/1019 for an example)
* each test case is "self-contained" so that the student sees meaningful output from the test runner (no forEach, no helper functions defined in other parts of the test file etc.)

Here is a general idea for the introduction that was discussed before:
Show how to do something like map or filter with a simple for loop, then show how to do it with the helper method instead. Afterwards provide a table with the common helpers. Just the method name as a link (e.g. to MDN) and a short explanation what this is for. We think its ok if the student reads up on some details of these methods on their own, we don't want to show and explain every single one in detail. Also the list can contain more things, than needed for the exercise (we count that info as "necessary to understand the concept" in contrast to "necessary to solve the exercise").

It might make sense to replace the `fill` task of the exercise (the last one) with `reverse` instead as that is probably more commonly used.

**Comment by TomPradat** [comment]
There is no `array-transformations` concept yet on this track. Does this issue mean that one should be created?

**Comment by junedev** [comment]
Good point. I didn't notice the folder does not even exist yet. Yes, the concept needs to be created and added to the config.json file.

**Comment by TomPradat** [comment]
Can I work on this?

**Comment by junedev** [comment]
Yes, that would be great! Note that I extended the issue description with some ideas about the introduction that I discussed with DJ but did not write down yet.

**Comment by junedev** [comment]
The array transformation concept exists now. The following tasks are left:

- [ ] Double check/improve the exercise as described above.
- [ ] Change the task that currently uses `fill` to instead teach `reverse`. Make sure to also adjust the hints, instructions etc.
- [ ] Add `sort` to the concept.
- [ ] Copy the concept introduction into the exercise introduction.

**Comment by junedev** [comment]
I will work on this so we can get the exercise live soon.
