### ISSUE TITLE
Additional Test Cases for GradeSchool given a same student add twice to different grade

### ISSUE THREAD

**Issue by andsus** [exercism/javascript#1337]
### Currently the test case does not test the above scenario.
- Given student A add to specific grade. E.g., Student A add to grade 2. And student B add to grade2
- When  student A is add again into different grade E.g., Student A add to grade 3
- Expected to see roster where Student A is in grade 3, and Student B in grade 2.

The GradeSchool exercise exists in many other track language, and this this use case is not tested across other tracks.

> Suggested to add more test case as follow:
```
// adding more test case
  it ('adding more students to the same grade and move same student to different grade for promotions', () => {
    gradeSchool.addStudent('Paul', 2)
    gradeSchool.addStudent('Blair', 2)
    gradeSchool.addStudent('James', 2)
    gradeSchool.addStudent('Paul', 3)

    const expectedDb = new Map(
      Object.entries({ 2: ['Blair', 'James'], 3: ['Paul'] })
    )
    expect(gradeSchool.studentRoster()).toEqual(expectedDb)
  })
```

Let me know how to get started on reviewing this issue?

**Comment by junedev** [comment]
Are you maybe looking at an older version of the tests? When I look at the current version I already see a test case for adding the same student twice in different grades: https://github.com/exercism/javascript/blob/da0d8b294701a3adf7723455a92146058978a2bb/exercises/practice/grade-school/grade-school.spec.js#L80

**Comment by andsus** [comment]
* What happen with Blair and James, when Paul move to grade 3? 
** Expect, Blair and James should still be in grade 2
> I've seen solution that wipe the entire grade 2, when Paul move from grade 2 to 3. 

That case is not covered in the current test case.

**Comment by junedev** [comment]
@andsus Ah ok, I got the point now.

The list of test cases for this exercise originate in another repository: https://github.com/exercism/problem-specifications

While it is possible to add extra test just for JavaScript, it is best to fix the shared content so all tracks benefit. Currently someone is in the process of fixing the grade school test cases, https://github.com/exercism/problem-specifications/pull/1837. I left them a note regarding your input.

**Comment by junedev** [comment]
Closing this as the person working on the grade school fixes confirmed they will incorporate your feedback.
