### ISSUE TITLE
Improve Concept Exercise "Elyses Enchantments" (Concept `arrays`)

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1339]
## Getting Started
Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

If you have not done so yet, it is probably also helpful to do a couple of "Learning Exercises" (this is how they are called on the site) yourself. You can also look at the code of an existing concept exercise like [`bird-watcher`](https://github.com/exercism/javascript/tree/main/exercises/concept/bird-watcher) (concept [`for-loops`](https://github.com/exercism/javascript/tree/main/concepts/for-loops)) for reference.

## Main Task
The current introduction.md file for "Elyses Enchantments" and the `arrays` concept is very minimal. It should be extended to include the basic information needed to solve the exercise. There are no lengthy explanations needed. That is what about.md is for. The following things should be introduced:
* accessing and changing an element
* basic methods to manipulate an array (push, pop, shift, unshift)
* how to remove elements with splice
* determining the length of an array

You can use the same content for the introduction.md of the exercise and of the concept.

## Bonus Tasks
While you are at it, you could also check whether other things need improvement.
* Make sure all info from the introduction is also included in the about.md
* Check whether about.md, instructions or hints needs improvement or additions
* Fill in the design.md file (you can find an example [here](https://github.com/exercism/javascript/blob/main/exercises/concept/amusement-park/.meta/design.md))

## How to proceed
1. **First accept this issue by saying "I'd like to work on this"** (no need to wait for a response, just go with it)
2. Use this issue to discuss any questions you have.
3. Create a PR and set "exercism/javascript" as reviewers. Additionally you can write in #maintaining-javascript on Slack that your PR is ready for review. Once you incorporated any critical feedback that the reviewer might give you and the PR is approved, it will be merged by a maintainer.

**Comment by InfiniteVerma** [comment]
I'd like to work on this

**Comment by junedev** [comment]
@pertrai1 Since there was no sign from @InfiniteVerma for over two weeks now, I will assign this issue to you instead. Please confirm you are still interested.

**Comment by pertrai1** [comment]
I am still interested. Thank you
