### ISSUE TITLE
Concepts to add

### ISSUE THREAD

**Issue by Steffan153** [exercism/javascript#1347]
There's quite a few (more advanced) concepts that I didn't see in the github issues. I thought it would be nice if these more advanced ones (at least some) could be covered too. Here's a list I cooked up:

- [ ] [JSON](https://javascript.info/json)
- [ ] [Generators and Iterators](https://javascript.info/generators)
- [ ] [Map](https://javascript.info/map-set)
- [ ] [WeakMap/WeakSet](https://javascript.info/weakmap-weakset)
- [ ] [WeakRef and FinalizationRegistry](https://v8.dev/features/weak-references)
- [ ] [BigInt](https://javascript.info/bigint)
- [ ] [Proxy and Reflect](https://javascript.info/proxy)
- [ ] [Symbol](https://javascript.info/symbol)
- [ ] [Decorators](https://blog.logrocket.com/understanding-javascript-decorators/)
- [ ] [Timeouts and Intervals](https://javascript.info/settimeout-setinterval)

Not sure if we should use all of these, but at least some would be nice :)

Thanks!

**Comment by junedev** [comment]
Topics are currently collected in this issue: https://github.com/exercism/javascript/issues/951

Please copy and paste your comment there.

I am working on a cleaner version of the concept roadmap, I will check whether your ideas are already on the new list.

**Comment by SleeplessByte** [comment]
(These are all great ideas and additions @Steffan153, and in full agreement with junedev)
