### ISSUE TITLE
Translation Service's Test Cases

### ISSUE THREAD

**Issue by AndrewLawendy** [exercism/javascript#1358]
This exercise test cases are not working correctly
For example:
- `Free service` can succeed with the following snippet
```javascript
free(text) {
  return this.api.fetch(text);
}
```

- `Request service` can succeed with the following snippet
```javascript
 request(text) {
    return this.api.fetch(text)
  }
```

- `Batch service` can succeed with the following snippet
```javascript
batch(texts) {
  return this.api.fetch([...texts])
}
```

- `Premium service` can succeed with the following snippet
```javascript
premium(text, minimumQuality) {
  return this.api.fetch(text);
}
```

**Comment by SleeplessByte** [comment]
Ugh. That shouldn't be the case. Thanks for reporting! If you know how to fix it, we accept PR's!

**Comment by AndrewLawendy** [comment]
Working on it...

**Comment by AndrewLawendy** [comment]
PR https://github.com/exercism/javascript/pull/1359 is merged
