### ISSUE TITLE
Falsy not truthy

### ISSUE THREAD

**Issue by halfmoongroup** [exercism/javascript#1382]
on line 34 of javascript/concepts/type-conversion/introduction.md

content is: 

> Note that because of the described rules, `'0'`, `'false'`, `[]` and `{}` are **thruthy** in JavaScript.

this is an error what's described is falsy, not truthy.

**Comment by junedev** [comment]
Although this might be surprising to you, the content is correct. Everything that is not on the list of things that are falsy (https://developer.mozilla.org/de/docs/Glossary/Falsy), is in fact truthy.  
Here you can see this in action in a REPL: https://replit.com/@junedev/thruthy#index.js
