### ISSUE TITLE
Promises Exercise may be missing tests

### ISSUE THREAD

**Issue by mmmmmrob** [exercism/javascript#1400]
https://github.com/exercism/javascript/blob/ba702157951d269f3ec70d968bd8573efd3a2ade/exercises/practice/promises/promises.spec.js

The tests for the promises exercise ensures each function returns a promise, but does not test for two scenarios:

1. What should happen if the function is called with no arguments (or nullish) rather than empty array

2. That the promise resolves when called with an empty promises array.

I spotted these because my own implementations pass all the tests but do not resolve when given an empty array.

I am happy to add tests if we agree they would add value.

**Comment by SleeplessByte** [comment]
Yep, that sounds good. Go for it!

**Comment by mmmmmrob** [comment]
Should there also be a test for the incoming promises array containing non-promise objects?
