### ISSUE TITLE
Promises Concept: About Footnotes Not Formatted

### ISSUE THREAD

**Issue by pertrai1** [exercism/javascript#1406]
It looks as though footnotes in the about.md file are not showing correctly:

![promises-footnotes](https://user-images.githubusercontent.com/442374/136126525-8f6779f4-206d-4fad-9900-4d94ec1458ee.jpg)

**Comment by junedev** [comment]
When I look at that page in a private browser window (so logged out) that also renders the about page but everything looks correct there. 
https://exercism.org/tracks/javascript/concepts/arrays

Also when I look at the introduction it looks correct.

🤔

**Comment by junedev** [comment]
This was fixed recently: https://github.com/exercism/website/pull/2040

Looks all good now.
