### ISSUE TITLE
VERY minor mistake in Poetry Club Door Policy exercise

### ISSUE THREAD

**Issue by Fbrufino** [exercism/javascript#1422]
Hi guys, this is a very minor thing, but I noticed 2 of the test descriptions have a small mistake. I actually did correct it locally in my code, but I'm not yet comfortable sending a PR and I haven't even set my Node environment up, so I'll just list the descriptions in question with my suggestions:

| Test | Current Description | Suggestion |
| ---- | --- | --- |
| Test 2 | "it _outputs takes_ the first characters" | "it takes the first characters" |
| Test 8 | "it _outputs takes_ the first characters" | "it takes the first characters" |

**Comment by Fbrufino** [comment]
> If you just want to fix typos like this, you can navigate to the file on GitHub and click on the edit button (pencil icon). It will automatically do all the needed things for you and point you towards submitting the PR after you are done editing. Want to give it a try?

Oh, I'm so sorry, I went out to try it and just realized that the [repository version](https://github.com/exercism/javascript/blob/main/exercises/concept/poetry-club-door-policy/door-policy.spec.js) is a bit ahead of the website, and that the problem is already taken care of in it.

So I guess the site should update soon, right? Again, not really comfortable closing the issue myself since I'm not 100% I understand how things work, lol. I'm sorry if this was just a waste of time.

**Comment by junedev** [comment]
Yes, there was an update to the exercise recently. You can get the new version on the website, when you click on the "outdated" warning sign or the "see what changed" banner.

It's perfectly fine if you close an issue that you opened and that is no longer relevant. I will do this now.
