### ISSUE TITLE
Add an automated PR comment

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1436]
Angelika created this great GitHub action that can generate PR comments depending on which files have changed in the PR.
https://github.com/exercism/pr-commenter-action

An example can be seen in the Elixir Track: https://github.com/exercism/elixir/pull/930#issuecomment-926567977

I was thinking about adding something similar for the JavaScript track.
It could take care of the following things:
* Remind the maintainer to set the correct size label.
* If concept about.md, introduction.md or exercise introduction.md for a concept exercise is changed, remind the contributor to check the change is applied consistently to all 3 files.
* If the exemplar or the stub is changed, remind the contributor to check that both files are kept in sync (same JSDoc comments, same function signatures).
* If a practice exercise introduction or test file is changed, remind the contributor to check whether the exercise originates in problem-spec and what to do in that case.

Any objections? Any thoughts on additional things the PR comment should cover?

**Comment by SleeplessByte** [comment]
Right. Yes. You are right. I meant that for practice exercises, the instructions should be like canonical, and only appends should be used to add things...
