### ISSUE TITLE
Nucleotide Count: Remove unnessary class

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1473]
The Nucleotide Count stub and exemplar solution currently contain a class definition that serves no purpose.
https://github.com/exercism/javascript/blob/0017b79c40521091794437fa0d0d9974de35c4d5/exercises/practice/nucleotide-count/nucleotide-count.js#L6-L7

The exercise should be changed so that the stub and exemplar only use a simple function definition, e.g.
```javascript
export function nucleotideCounts(strand) {
   // ...
}
```
The following files need to be updated:
* `nucleotide-count.js`
* `nucleotide-count.spec.js`
* `.meta/proof.ci.js`
* root level `config.json` (remove "classes" from the prerequisites of the exercise)

You can find general information about the structure of practice exercises here: https://exercism.org/docs/building/tracks/practice-exercises

**Comment by lpizzinidev** [comment]
Hi! Can I work on this issue?

**Comment by junedev** [comment]
Sure, I'll assign you. Thanks Form helping out.
