### ISSUE TITLE
Nucleotide Count: Describe output format in instructions

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1474]
The JavaScript version of the Nucleotide Count exercise requires the student to format the output like this `'20 12 17 21'` instead of returning an object `{ A: 20, C: 12, ...}`. Its a good exercise to format the output put currently the required format is not described anywhere and needs to be guessed from the tests.

The task is to add an `instructions.append.md` file in the `.docs` folder. In that file the required output format should be described. The content of the file will later be rendered right below the content of `instructions.md`.
You can see an example of such an append file here: https://github.com/exercism/javascript/blob/main/exercises/practice/protein-translation/.docs/instructions.append.md?plain=1

You can find general information about the structure of practice exercises here: https://exercism.org/docs/building/tracks/practice-exercises

**Comment by DavidMatalik** [comment]
I take this issue.
