### ISSUE TITLE
Concepts Numbers and Arithmetic Operators: Improve about.md content

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1505]
It would be good to check the about.md files of the concepts `numbers` and `arithmetic-operators` for possible improvements/additions. This task has a lower priority but if someone is interested in working on this, please volunteer.

For example in the about.md for `numbers` it would be good to make sure the special "numbers" NaN, and +/- Infinity are explained well. Also it would be good to show that/how you can write numbers with exponential and underscore notation.

Here some ideas for the about.md of `arithmetic-operators`:
- behavior of `%` if one operand is negative, see [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder) below the demo box
- clarify difference between remainder and modulo operator in some other languages
- typical use of `%` for keeping a value inside a range/ "if you reach the end while iterating, start from the beginning" (not sure how to describe this well but explanation should also be understandable for someone who does not know ring theory)

The general documentation on concepts can be found here: https://exercism.org/docs/building/tracks/concepts

**Comment by cydeb33** [comment]
Hello, I'd like to participate on this issue if possible !

**Comment by junedev** [comment]
@cydeb33 Welcome! Great that you want to help. I will assign this issue to you. Take the time you need. I would only ask you to let us know in case you decide to not work on this any more for whatever reason so we can re-assign the task.

**Comment by cydeb33** [comment]
Sure thing ! 
I had a question regarding the structure of the "about.md" (forgive me if it's already explained somewhere).
When adding new information, let's say about +- infinity, do I just add it where I feel it makes sense or do I add it at the bottom ?
Thanks in advance

**Comment by junedev** [comment]
You can add content whereever you want. In general, feel free to adjust the existing about.md content as needed.

**Comment by cydeb33** [comment]
I have finished adding information the the numbers "about.md", I'm quite unexperienced with GitHub, should I add the file here for you to take a look or should I do a PR directly?

**Comment by junedev** [comment]
You create a fork of the repository, you make your changes in that fork and then create a PR from there to the original repo. A maintainer (e.g. me) will then review your changes and potentially ask you to make some changes. Then if everything is in order, the PR gets merged.

Just in case you need more information about how to create the fork and the PR, this might help: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by cydeb33** [comment]
Amazing thanks for your help!

**Comment by junedev** [comment]
The PR mentioned above wasn't finished but might serve as a starting point.

**Comment by SyllightTheway** [comment]
Hi, I would like to volunteer on this issue.

**Comment by junedev** [comment]
I am closing this issue, the most important parts were addressed by the PR above.
