### ISSUE TITLE
Add extra test: Prevent assigning value to `balance` property in "Bank Account" exercise

### ISSUE THREAD

**Issue by kshivakumar** [exercism/javascript#1520]
The "Bank Account" exercise should have a test case that raises `ValueError` when directly assigning value to `balance` property.

Below code(many user submissions have similar code) passes all the current test cases:
```javascript
class BankAccount {
  constructor() {
    this.isActive = false
    this._balance
  }

  open() {
    if (this.isActive) throw new ValueError()
    this.isActive = true
    this.balance = 0
  }

  close() {
    if (this.isActive) this.isActive = false
    else throw new ValueError()
  }

  deposit(amt) {
    if (amt < 0) throw new ValueError()
    this.balance += amt
  }

  withdraw(amt) {
    if (amt < 0 || amt > this.balance) throw new ValueError()
    this.balance -= amt
  }

  get balance() {
    if (!this.isActive) throw new ValueError()
    return this._balance
  }

  set balance(amt) {
    this._balance = amt
  }
}

class ValueError extends Error {
  constructor() {
    super('Bank account error');
  }
}
```
There's no test case that raises error on doing
```javascript
let ba = new BankAccount()
ba.balance = 100 // Expected ValueError
```

**Comment by junedev** [comment]
@kshivakumar Thanks for pointing this out but I am not sure what you have in mind with regards to a test case here. How would a test case that catches this type of error look like?

Maybe this is rather something the [analzyer](https://exercism.org/docs/building/tooling/analyzers) could pick up and give feedback for.

**Comment by kshivakumar** [comment]
@junedev I have the below test case in mind:
```javascript
test('direct assignment of balance throws error', () => {
    const account = new BankAccount();
    account.open();
    expect(() => {
      account.balance = 100;
    }).toThrow(ValueError);
  });
  ```

**Comment by junedev** [comment]
Ah, ok, now I understand what you mean.

Your new test case would require all students that currently correctly don't provide a setter to add one so they can pass the new test. (In case they want to keep their solutions up to date.)

I was thinking how we could avoid that. What do you think about adding a test case that calls something like `ba.balance = 9999` and then we check that this did not modify the actual internal balance.

**Comment by kshivakumar** [comment]
> Ah, ok, now I understand what you mean. I misunderstood your issue before, sorry!

No problem!

> Your new test case would require all students that currently correctly don't provide a setter to add one so they can pass the new test. (In case they want to keep their solutions up to date.)

I was afraid this would happen. I am curious if there's a playbook for handling this scenario. I guess this is not the first time such an issue has come up, after all, as more and more users solve the exercises more edge cases are revealed.

For the new test case to pass, `set` needs to be defined like:
```javascript
set balance(v) {
  throw new ValueError()
}
```

> I was thinking how we could avoid that. What do you think about adding a test case that calls something like `ba.balance = 9999` and then we check that this did not modify the actual internal balance.

Such a test case will fail if the solution defines a `set` method and pass if the `set` method is not defined. I skimmed through several community solutions and both the implementations occur in good numbers.

**Comment by junedev** [comment]
@kshivakumar Don't get me wrong, it is totally fine to fail old solutions if it is necessary to improve the exercise. But in the case of this exercise, not having a setter at all is a perfectly valid solution so I don't really feel good about failing those solutions with your new test case now, given there is an alternative how we can fail the solutions that are actually wrong. "No setter" also seems to be the approach taken in other languages, e.g. https://github.com/exercism/csharp/blob/main/exercises/practice/bank-account/.meta/Example.cs.

**Comment by kshivakumar** [comment]
@junedev Fair enough 👍🏽 , closing the issue.

**Comment by junedev** [comment]
@kshivakumar I am re-opening the issue. We still need that addition

**Comment by junedev** [comment]
@kshivakumar I am re-opening this issue as we still need an additional test case to make sure to fail the solutions with a setter, just in a different form to what you originally suggested.

**Comment by kshivakumar** [comment]
@junedev Something like
```javascript
  test('direct balance assignment should not change actual balance', () => {
    const account = new BankAccount();
    account.open();
    account.deposit(100);
    account.balance = 999
    expect(account.balance).toEqual(100);
  });
```
??

If yes, can I raise a PR for the same?

**Comment by junedev** [comment]
Yes, exactly. A PR would be great!

**Comment by kshivakumar** [comment]
> ```js
>   test('direct balance assignment should not change actual balance', () => {
>     const account = new BankAccount();
>     account.open();
>     account.deposit(100);
>     account.balance = 999
>     expect(account.balance).toEqual(100);
>   });
> ```

The above test case fails as expected when a solution uses `setter` because `balance` is modified.
But it raises `TypeError: Cannot set property balance of #<BankAccount> which has only a getter` when the solution doesn't define the `setter`, even if `balance` is not modified.
That means, the test case raises two different type of errors based on the presence of `setter`.

The correct test case is probably,
```js
test('direct balance assignment should not change actual balance', () => {
  const account = new BankAccount();
  account.open();
  expect(() => {account.balance = 999}).toThrow(ValueError);
});
```
and that would require the solution to contain
```js
set balance(_) {
  throw new ValueError
}
  ```
The above test case sounds like "Don't allow assignment" whereas the one that we finalised earlier sounds like "Allow assignment but ensure value doesn't change". First one can be considered a good practice since you are preventing an error at the root.

**Comment by junedev** [comment]
Thanks for the update. I wasn't aware of that error. 🙈 From what you said the test case should check that this type error is thrown for an assignment to balance. Any idea how to  make it a bit more clear that we are not expecting the student to throw that error by hand?

**Comment by kshivakumar** [comment]
If the test case expects `TypeError`, solution doesn't need to have the `setter` method defined.
If the test case expects `ValueError`, solution needs to explicitly define a `setter` method and raise `ValueError` inside the body.

Second option is more explicit as it encourages the student to think about `setter` whenever they define a `getter`. 
Also, we are using `ValueError` for all banking related errors, it makes sense to use it in this case as well.

Since this is a "easy" practice, how about we add the `setter` method that raises ValueError in the skeleton code? Will it become too easy for the student? Should we just have an empty `setter` method?

**Comment by junedev** [comment]
We circled back to the no setter vs. setter with ValueError decision. Let me propose a compromise before I ask a senior maintainer to make a call here.

What about the new test just checks that an error is thrown when trying to assign a balance but does not require a specific error type, just any `Error`. That way no setter and a setter that throws an error would both pass the tests which makes sense since both are valid solutions to the problem. WDYT?

**Comment by kshivakumar** [comment]
That's a good idea, raising a PR.
