### ISSUE TITLE
Freelancer Rates exercise gives incorrect feedback about missing function 

### ISSUE THREAD

**Issue by NextNebula** [exercism/javascript#1521]
The analyser gives for the Freelancer Rates exercise gives incorrect feedback about a missing functions. It says it misses a function called monthRate. This is a function that is not asked in the exercise specifications. The analyser is probably build for a older spec of the exercise.

**Comment by junedev** [comment]
@SleeplessByte Can we turn the analyzer off somehow until it is updated.

Because I saw this being draft and mentioning its waiting for the update of the exercise, I assumed there was no analyzer yet. https://github.com/exercism/javascript-analyzer/pull/121 :see_no_evil: Sorry!

**Comment by SleeplessByte** [comment]
Yes. Will fix it tonight

**Comment by SleeplessByte** [comment]
It was merged! Try again

**Comment by NextNebula** [comment]
Fixed!

**Comment by SleeplessByte** [comment]
Fijn :)
