### ISSUE TITLE
ci-check script is rather slow

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1599]
The script [ci-check](https://github.com/exercism/javascript/blob/main/scripts/ci-check) which in turn calls some other scripts runs for every exercise that was changed in a PR. That means e.g. for PRs that include some files being synced for all exercises, the script runs for all exercises. As far as I could see, this consistently takes 10-15min when run as part of the GitHub Actions.

Examples:
- https://github.com/exercism/javascript/runs/4600717991?check_suite_focus=true
- https://github.com/exercism/javascript/runs/4679060545?check_suite_focus=true

![image](https://user-images.githubusercontent.com/12543047/147856809-7f928932-6fcf-4cd2-917d-608dba62dd63.png)

This is a bit annoying when a maintainer wants to get something done quickly so maybe someone has an idea what could be done to improve the performance.

**Comment by SleeplessByte** [comment]
No longer slow!
