### ISSUE TITLE
Why does Exercism test for state mutation?

### ISSUE THREAD

**Issue by arnthorsnaer** [exercism/javascript#1604]
In JS track Bird Watcher exercise Test 9 is testing for object equality. The only way for me to pass the test is to mutate the array. My initial solution where I returned a new array with the modified value triggers this test failure. It means that my map solution was not accepted. Is this intended behaviour?

```
const birdsPerDay = [2, 0, 1, 4, 1, 3, 0];
expect(Object.is(fixBirdCountLog(birdsPerDay), birdsPerDay)).toBe(true);
```

```
Error: expect(received).toBe(expected) // Object.is equality
Expected: true
Received: false
```

**Comment by SleeplessByte** [comment]
(I've moved the ticket)

As a maintainer, I don't know what action we could take. This test is warranted given the instructions, ánd per the learning goals we don't want people to use `map`.

>  For example someone can use a for loop to solve this without mutating state. However I can't think of any alternatives to this so perhaps it's an acceptable constraint.

Is this the unwanted side-effect? 

Given side-effects, you can still use map, which is why we're also implementing a check in the analyzer to further discourage it.

```javascript
// Intended
export function fixBirdCountLog(birdsPerDay) {
  for (let i = 0; i < birdsPerDay.length; i += 2) {
    birdsPerDay[i]++;
  }
  return birdsPerDay;
}

// Don't do this, but you could...
export function fixBirdCountLog(birdsPerDay) {
  birdsPerDay.map((value, index, self) => {
    if (index % 2 === 0) {
      self[index] = value + 1
    }
  })

  return birdsPerDay;
}
```

`array-transformations` does the opposite, btw. It will check if you use a `for` loop and nudge you to `map` instead.

**Comment by arnthorsnaer** [comment]
>Is this the unwanted side-effect?

My point was the test not only promotes `for-loops` but requires state mutation. However it's possible to use a `for` to solve this and return the correct result but this will not pass the test. The description ("returns that same array") does imply that this is the intention. I understand if the state mutation requirement is a means to an end (for loops) but I understand it a bit less if it's an end in itself. 

Anyways, I don't intend this to be a debate. This just seemed very odd to me. Thanks for your response @SleeplessByte

**Comment by joshgoebel** [comment]
>  The description ("returns that same array") does imply that this is the intention.

Would "returns/mutates the same array" be clearer?

**Comment by junedev** [comment]
I think in other exercises we say "returns the modified array" (or object in other contexts). That might help here as well.
In general I think it makes sense to have a task that uses a for loop and mutates an array as it is a common use case.

**Comment by arnthorsnaer** [comment]
I think those changes in description make it clearer.

**Comment by junedev** [comment]
I re-opened the issue so we don't forget to make the change.
