### ISSUE TITLE
Ozan Playlist Not Using Sets

### ISSUE THREAD

**Issue by ievgenk** [exercism/javascript#1715]
Heya good people of Exercism, 

Was just doing Ozan Playlist exercise and noticed that even though concept linked is "Sets" the exercise is using arrays instead. Is this intentional or has not been converted to sets yet? 

Maybe I could help with that ?

Thanks for wonderful learning resource !

**Comment by pjohanneson** [comment]
No, I agree with your initial assessment. I have apparently "mastered" sets without actually *using* a set.

For me it boiled down to:
- use arrays, which I already understood and the exercise seemed to require; or
- use sets internally, then convert the sets back to arrays for the `return`. (But I didn't see anything in the lesson explaining how to convert from one to the other.)

That said, I've been finding Exercism a very, very useful online resource.
