### ISSUE TITLE
Many tests are being skipped

### ISSUE THREAD

**Issue by ievgenk** [exercism/javascript#1726]
Hello,

Just wondering how come many tests in exercises are commented out with the "xtest"? Some of the quick examples are both of the Resistor exercises and Gigasecond ones. 

When I uncomment them they seem to operate as expected, and with them being skipped one could make mistakes in the code and still pass the assignment.

Is it something I can submit a pr for ?

Thank you as always for a wonderful resource.

**Comment by SleeplessByte** [comment]
Hi there!

The explanation can be found in a few places, including [Testing on the JavaScript track](https://exercism.org/docs/tracks/javascript/tests#h-understanding-skip-tests).

> **Why they are skipped ?**
> To enable users to concentrate on one test at a time and enable one by one as they evolve the solution.
> 
> **How to enable them ?**
> Change `xtest` to `test`.

**Comment by ievgenk** [comment]
My apologies for not seeing this myself, thanks for taking time to reply!
