### ISSUE TITLE
Elyses enchantments: Tests requires a solution with mutations

### ISSUE THREAD

**Issue by luckysoni** [exercism/javascript#1770]
The spec has tests that require mutation of the array being passed to the function being tested. This restricts users to submit solutions that use immutability.

Consider the following test:
```
test('adding multiple cards to the stack to the bottom', () => {
    const stack = [1];

    insertItemAtBottom(stack, 5);
    insertItemAtBottom(stack, 9);

    const expected = [9, 5, 1];
    expect(stack).toStrictEqual(expected);
  });
```

The assertion is being made on the original `stack` which will require it to be mutated.

I am happy to fix the tests if folks agree that this Is suboptimal.

**Comment by SleeplessByte** [comment]
This is intentional, because we want to teach people how to _mutate_ the array.
