### ISSUE TITLE
allowing mentor more access to mentee exercise even if they are not done

### ISSUE THREAD

**Issue by Danbaba1** [exercism/javascript#1794]
i have realised you have to finish an exercise before requesting a mentor. this should be changed and mentors should have more access to see the code and alter the code of their mentee.

**Comment by junedev** [comment]
@Danbaba1 Thanks for leaving a note. The issue you mention was already raised here https://github.com/exercism/exercism/issues/6187 so I will close this one as duplicate. If you have more thoughts on this, feel free to post them in the existing issue.
