### ISSUE TITLE
Fruit Picker: Find (new) home for arrow functions concept

### ISSUE THREAD

**Issue by junedev** [exercism/javascript#1819]
Because of https://github.com/exercism/javascript/pull/1725, the fruit picker concept exercise no longer includes tasks that require arrow functions. That means we need to find a (new) home for arrow functions. Here some options:
* A - Add a new concept exercise that teaches arrow functions
* B - Add arrow functions as a concept to one of the Elyses Enchantments exercises that teach array methods and heavily use arrow functions.
* C - Extend fruit picker to include tasks where arrow functions make sense and keep arrow functions as part of fruit picker

See also https://github.com/exercism/javascript/pull/1725#discussion_r895882668 for more background.

**Comment by junedev** [comment]
@Endzelisp Thanks for leaving a note. The fruit picker exercise was completely reworked and the change became available on the website 2 days ago. Did you already update to the new version? You should see an orange banner on the exercise page that allows you to do the update. If you didn't update yet, I recommend you try out the new version first. If you still have issues with the new version, then please create a new issue about it. This issue here is meant only for discussing the arrow functions part.

**Comment by SleeplessByte** [comment]
@Endzelisp I am going to hide these messages to not confuse others, but feel free to open a new issue if you still have thoughts!

**Comment by junedev** [comment]
I will work on this and go for option B for now.
