### ISSUE TITLE
Improve Scale Generator tests

### ISSUE THREAD

**Issue by dem4ron** [exercism/javascript#1906]
Hey!

I'd like to suggest some improvements on the Scale Generator tests.

I think [in this form](https://github.com/exercism/javascript/blob/main/exercises/practice/scale-generator/scale-generator.spec.js) these tests are not correct. 

The `intervals.length` should be `scale.length - 1`.

```diff
    test('Simple major scale', () => {
-      const expected = ['C', 'D', 'E', 'F', 'G', 'A', 'B'];
+      const expected = ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'];
      expect(new Scale('C').interval('MMmMMMm')).toEqual(expected);
    });
```

Check the walkthrough at the end of [problem-specs description.](https://github.com/exercism/problem-specifications/blob/main/exercises/scale-generator/description.md), or tests in other languages, e.g. [Rust](https://github.com/exercism/rust/blob/main/exercises/practice/scale-generator/tests/scale-generator.rs#L64-L66)

This change breaks the _proof_ solution, which I think is a good solution but not ideal if you'd like to generate scales based on any random input in this system. e.g. `AAAAAAAAAAAA`

I'd also suggest updating the instructions.md, as it seems to be behind the [problem-specs description.](https://github.com/exercism/problem-specifications/blob/main/exercises/scale-generator/description.md)

**Comment by SleeplessByte** [comment]
Resolved in https://github.com/exercism/javascript/pull/1907
