### ISSUE TITLE
Possible typo in implementing-a-concept-exercise.md

### ISSUE THREAD

**Issue by SalahuddinAhammed** [exercism/javascript#1920]
Shouldn't it be `<slug>.js` instead of `<slug>.cs` at line 93?

**Comment by SleeplessByte** [comment]
Is that file in this repository?

**Comment by SalahuddinAhammed** [comment]
Affected file: https://github.com/exercism/javascript/blob/main/reference/implementing-a-concept-exercise.md

In the affected file at line 93, it says "`<slug>.cs`. the stub implementation file......". But the file tree presented in README shows `<slug>.js`.
Again when creating a pull request, the auto generated comment says "or the stub file `<exercise>.js`....". Here the file extenstion is also `.js`. So maybe it is a typo in the affected file.

**Comment by SleeplessByte** [comment]
You are correct! Would you like to submit a PR to update this file and rename `.cs` to `.js`?

**Comment by SalahuddinAhammed** [comment]
Yes. Opening a PR soon.
