### ISSUE TITLE
Test suite failed to run

### ISSUE THREAD

**Issue by madzi-hove** [exercism/javascript#1932]
Hi. I am working on the javascript track and am currently doing the translation exercise. I am using the online editor and receiving this error when ever i try to run tests We received the following error when we ran your code:

● Test suite failed to run

Cannot find module 'core-js/modules/es.array.push.js' from '../../api.js'

Require stack:
/api.js
/service.spec.js

![Screenshot (6)](https://user-images.githubusercontent.com/82516667/193572092-6042f60f-3be4-4ec8-91ef-168e1821476c.png)

I have refreshed the page, flushed the browser cache,reverted the exercise to start and still this keeps appearing without adding any new code.. Any help will be greatly appreciated. 

I have also noticed that all my exercises are unlocked even though I am in learning mode.

**Comment by SleeplessByte** [comment]
Hi @madzi-hove, this is not your fault. Working on a fix.

All your exercises being unlocked is not my doing / a separate issue.

**Comment by SleeplessByte** [comment]
I've disabled experimental features for now (no proposal syntax allowed) and this seems to have resolved the issue, for now. Feel free to retry @appovo .

**Comment by SleeplessByte** [comment]
I've disabled experimental features for now (no proposal syntax allowed) and this seems to have resolved the issue, for now. Feel free to retry @madzi-hove .

**Comment by madzi-hove** [comment]
The tests are running now, thank you very much.

**Comment by SleeplessByte** [comment]
If you run into it again, please open another issue and feel free to ping me
