### ISSUE TITLE
Screen is not responsive on smaller devices on donate page

### ISSUE THREAD

**Issue by hirentimbadiya** [exercism/javascript#2126]
On width  less than 500 px the donate page is not responsive it overflows like this -> 
![issue donate](https://user-images.githubusercontent.com/86219935/229285233-60b188d9-e228-4ccb-96b3-3f24de477c76.png)

Desired Solution -> it should be responsive for all resolutions.

**Comment by SleeplessByte** [comment]
See https://github.com/exercism/exercism/issues/6036
