### ISSUE TITLE
wrong solution to testcase

### ISSUE THREAD

**Issue by keerthinannepamula1** [exercism/javascript#2472]
![new-issue1](https://github.com/exercism/javascript/assets/160098716/b9c31f40-bbb5-4cdf-8b7f-1f121c9307e8)

The solution to the test-17: _the canFreePrisoner method returns true when everyone is sleeping and the pet dog is present_ is supposed to false. 
My logic: how can Annalyn save the prisoner when prisoner is sleeping and also its given clearly in the instructions that the prisoner cannot be asleep? 
please correct me if I'm wrong.

**Comment by SleeplessByte** [comment]
If I interpret the instructions I read: If the dog is there, the knight won't do anything. As long as the archer is asleep, Annalyn can safely wake the prisoner. If the dog isn't there, the prisoner needs to be ready from the get-go, or there won't be enough time.
