### ISSUE TITLE
Issues on unit tests of Markdown exercise 

### ISSUE THREAD

**Issue by M-AminAlizadeh** [exercism/javascript#2474]
Hey there

According to the [Markdown Exercise](https://exercism.org/tracks/javascript/exercises/markdown) after installing the packages while 
testing the code it shows an error because in the `markdown-spec.js` file there is a mistake (typo issue) of `xtest` instead of `test`

![Screenshot from 2024-05-30 15-49-08](https://github.com/exercism/javascript/assets/67329484/bb37696f-8c40-46be-88d5-7e8038917642)

--- 
I can fix it and make the PR for it 
Kindly let me know if it's ok

**Comment by SleeplessByte** [comment]
(As written on the forum, this is a `bun` issue, not an exercise issue and not a typo 😄)
