### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/javascript#2536]
@Cool-Katt You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by Cool-Katt** [comment]
I somehow never saw this coming.
I would love to help as much as I can, but I have to be upfront, I will probably not be able to be 100% dedicated all the time. If you're okay with that, I can see what I can do.

Also, this isn't replacing JD, right?

**Comment by ErikSchierboom** [comment]
Awesome. Thank you!

> I will probably not be able to be 100% dedicated all the time

That's perfectly fine!

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)

**Comment by SleeplessByte** [comment]
JD is still here ;)

@Cool-Katt just keep doing what you're doing. No need to invest _more_ time but all your help is very appreciated.

**Comment by Cool-Katt** [comment]
Well, thank you all in that case.

**Comment by Cool-Katt** [comment]
@ErikSchierboom & @iHiD 
As I found out from #2559, I apparently don't have write access to the repo so I can't merge PRs. 
Is this how it's supposed to be or something got misconfigured?
