### ISSUE TITLE
Simplify hello-world exercise

### ISSUE THREAD

**Issue by behrtam** [exercism/javascript#333]
> Hey guys, was wondering how people solved the Hello World test for the javascript language. I'm kind of stuck on the second test, and I'm not sure how to approach it.

I just had a guy in the gitter chat, starting with javascript and he got directly stuck when solving the hello-world exercise. Maybe you should also simplify the `hello-world` exercise like other tracks did.

*Background: https://github.com/exercism/x-common/issues/520, https://github.com/exercism/x-common/pull/544*

**Comment by matthewmorgan** [comment]
@behrtam thanks for taking point on that one.  Is the user OK, or do we need to engage with him on this?

**Comment by rchavarria** [comment]
I'd label this issue as "good first patch". Issue https://github.com/exercism/x-common/pull/544 is clear, and it should be easy to simplify `hello-world` exercise.

Any help is welcome.

**Comment by matthewmorgan** [comment]
@jeffreydking04 contacted me regarding tackling this problem.  Jeffrey, have at it!

I know you had some contact with @kytrinyx as well, please let me know how I can help you move on this.

**Comment by tejasbubane** [comment]
@jeffreydking04 Are you working on this?

**Comment by jeffreydking04** [comment]
@tejasbubane I intend to do this.  I got caught up in a job interview project for the last couple weeks and slid this to the back burner.  If you want to jump on it, feel free, but if you do not, I still plan on it.

**Comment by tejasbubane** [comment]
@jeffreydking04 No worries, get back to it when you are free. I was wondering since I did not see any comment of yours.

**Comment by KamilMalek** [comment]
Since I haven't seen any activity for the past two month, I've decided to tackle the issue on my own.

**Comment by jeffreydking04** [comment]
@KamilMalek, Thanks for taking this on.  I started a new job immediately after I started contributing and I have been devoting all my energy to that endeavor.
