### ISSUE TITLE
Add linting to Makefile

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/javascript#373]
We shouldn't require reviewers to comment on things like whitespace, semicolons, etc that a linter can easily call out.

This story is _not_ to lint exercise code that users are working on.  It is for submissions to the `exercism/javascript` repo.

Success Criteria:
- ESLint is integrated into the development workflow either with an `.eslintrc` file, or the appropriate config in `package.json`
- code is linted as part of the `make test` task.

**Comment by KamilMalek** [comment]
Not sure about it, but here is my proposal

**Comment by matthewmorgan** [comment]
Awesome!  We have some prior work on the Ecmascript track that we can use for guidance here.  I've made more details comments on your PR.

This is an important change that will really help move the track forward.  Let me know how I can help further.

**Comment by rchavarria** [comment]
#399 is still open, but as #411 has been merged, I think this issue can be closed.
