### ISSUE TITLE
Possible inconsistency with Bob JavaScript test spec regarding "Whoa, chill out!" response

### ISSUE THREAD

**Issue by rclai** [exercism/javascript#376]
Continued from https://github.com/exercism/exercism.io/issues/3579.

__Original post:__

If I'm not mistaken, the specs that determine whether Bob will respond with "Whoa, chill out!" require that all alphabetical characters be uppercase.

However, the following test spec seems to invalidate that rule because all alphabetical characters are uppercase but Bob responds with "Whatever.":

```
it('calmly speaking about umlauts', function() {
  var result = bob.hey('\xfcML\xe4\xdcTS');
  expect(result).toEqual('Whatever.');
});
```

If I were to speak calmly about umlauts to Bob, shouldn't there be some lowercase alphabetical characters?

**Comment by rclai** [comment]
In reply to https://github.com/exercism/exercism.io/issues/3579#issuecomment-312478071 @NobbZ, I see.

It didn't occur to me that there can be lowercase umlauts, thereby making that not a yell.

**Comment by rclai** [comment]
Action item: https://github.com/exercism/exercism.io/issues/3579#issuecomment-312478071

**Comment by matthewmorgan** [comment]
@rclai Thanks for pointing this out!  BTW any time you see an issue like this, you are welcome to make a PR.  Although I've done this one, a similar change will need to be done to the EcmaScript track.  LMK if you're interested and if I can assist.

**Comment by rchavarria** [comment]
Absolutely!

@rclai, feel free to open a similar issue in https://github.com/exercism/ecmascript and do a similar PR as @matthewmorgan did on #377

**Comment by rclai** [comment]
Thanks.
