### ISSUE TITLE
Nextercism configuration

### ISSUE THREAD

**Issue by rchavarria** [exercism/javascript#382]
As stated in #381, Exercism will be moving to a tree-shaped track rather than a linear one, as described in the [progression & learning in Exercism](https://github.com/exercism/docs/blob/master/about/conception/progression.md) design document.

So, some tasks must be done: 

- [x] Add a rough estimate of difficulty to each exercise (scale: 1-10) if it hasn't already one
- [x] Add topics to exercises that has no topics yet
- [x] Choose *at most 20 exercises* to be core exercises (set `core: true`, and delete the `unlocked_by` key)
- [x] For each exercise that is not core, decide which exercise is the prerequisite (max 1)
- [x] If possible, leave 3 or 4 simple exercises as (`core: false`, `unlocked_by: null`), as this will provide new participants with some exercises that they can tackle even if they have not finished the first core exercise.

**Comment by rchavarria** [comment]
I started working on branch [nextercism-config](https://github.com/exercism/javascript/tree/nextercism-config).

I plan to push commits as soon as they're ready, so that anyone can work on this branch too.

**Comment by rchavarria** [comment]
Following @matthewmorgan's advice, copying Java guys, I've created a [spreadsheet](https://docs.google.com/spreadsheets/d/1pELRlzUlCSea5ybbBslFgoeLgDOkRZUjqZxN4ch2_1o/edit?usp=sharing) with current JavaScript exercises, I chosed 19 core exercises and unlocking exercises for non-core ones.

Of course, the spreadsheet shouldn't be the truth, so feel free to comment or edit it.

When everything looks more or less decided, I'll change `config.json` to reflect changes.

There aren't 3 or 4 exercises with `core: false`, `unlocked_by: null`. I think these exercises coudl be good candidates: queen-attack (difficult), pig-lating (easy), minesweeper (game, difficult), roman numerals (very well known).

Spreadsheet link: https://docs.google.com/spreadsheets/d/1pELRlzUlCSea5ybbBslFgoeLgDOkRZUjqZxN4ch2_1o/edit?usp=sharing

**Comment by matthewmorgan** [comment]
@rchavarria thanks for doing this.

A question: according to your task list above, the `core: false` exercises should be "simple." But, I don't think queen-attack or minesweeper would qualify as simple in the context of this track.  IS the requirement to use simple exercises or any exercises?

**Comment by rchavarria** [comment]
Ideally, I think *core* exercises should be simple or easy to solve. I see *core* exercises as doors/bridges to more complex and interesting exercises.

In the case of queen-attack or minesweeper, I know they're not easy, but they open the way to some exercises related to games. They don't have to be in the first place, maybe they can be in the 16th place (out of the 20 core exercises).

If there is another exercise, that is simpler, and could be seen as a *game* or is related in some way to queen-attack or minesweeper, it'd be awesome. If that exercise is not implemented in this track, why not add it? Don't worry, I can help 😉

**Comment by rchavarria** [comment]
Closing this because tasks have been don in #383 and #386
