### ISSUE TITLE
Change README from xJavascript to Javascript

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#396]
This repository was renamed from `xjavascript` to `javascript`. Change the README to reflect the change.

- [ ] Change the title
- [ ] Change the travis build URL to use https://travis-ci.org/exercism/javascript

**Comment by dgrskovic** [comment]
Hi!
Can I take this one, please?

**Comment by dgrskovic** [comment]
Ok, thanks.
It's done.
