### ISSUE TITLE
Configure ESLint to lint source code at development time

### ISSUE THREAD

**Issue by rchavarria** [exercism/javascript#44]
As discussed in [exercism/xjavascript#101](https://github.com/exercism/xjavascript/issues/101) and [exercism/xjavascript#26](https://github.com/exercism/xjavascript/issues/26), ESLint seems to be a good tool to lint JavaScript and ECMAScript source code.

Add it and configure it to lint source code at development time.

**Comment by rchavarria** [comment]
[exercism/docs#54](https://github.com/exercism/docs/issues/54) highly recommends the use of linters for all languages.

**Comment by rchavarria** [comment]
ESLint tool has been added in #81. Now, it's time to decide what should be linted and in what way. ESLint has lots of [rules](http://eslint.org/docs/rules/) that can be checked, organized in several groups:

- [ ] [Possible errors](http://eslint.org/docs/rules/#possible-errors)
- [ ] [Best practices](http://eslint.org/docs/rules/#best-practices)
- [ ] [Strict mode](http://eslint.org/docs/rules/#strict-mode)
- [ ] [Variables](http://eslint.org/docs/rules/#variables)
- [ ] [Node.js and CommonJS](http://eslint.org/docs/rules/#nodejs-and-commonjs)
- [ ] [Stylistic issues](http://eslint.org/docs/rules/#stylistic-issues)
- [ ] [ECMAScript 2015](http://eslint.org/docs/rules/#ecmascript-6)

**Comment by matthewmorgan** [comment]
@rchavarria At first consideration, without getting in to each of the available rules, it seems like we can omit two groupings:
1) Node.js and CommonJS: doesn't seem relevant.  Am I wrong?
2) Strict mode: this declaration is not needed in ES6, right?

Include some:
1) Possible errors (most if not all)
2) Best practices (most if not all)
3) Variables (most if not all)
4) ES 2015 (some of this seems like it belongs in 'stylistic'?)

@kytrinyx On the 'stylistic issues,' should exercism be expressing an opinion on this, or should that be left to discussion between users? Do other tracks that lint express opinions about style?

**Comment by kytrinyx** [comment]
I think the stylistic questions should be left to the users in languages where there's traditionally more than one way to do things. In Python and Go, for example, it would make sense to encourage following the standard style guide. In Ruby (and probably JavaScript...) not so much!

**Comment by matthewmorgan** [comment]
I think this is resolved.  Please let me know if not.  Thanks everyone!

**Comment by rchavarria** [comment]
In my opinion, there's still some work to do here. Well, I have to admit that there hasn't been too much activity related to this issue recently, but there are some point like: *Best practices* or *Variables* that I would like to address (see [comment](https://github.com/exercism/xecmascript/issues/44#issuecomment-159076263) above).

Are you ok with this? We could open a different issue, but I would prefer to reopen this one.

**Comment by matthewmorgan** [comment]
@rchavarria of course!  that's why I asked.  Sorry for overlooking the remaining tasks.

**Comment by tejasbubane** [comment]
@rchavarria Do you have any plans/ideas about implementing the `best practices` and `variables` you mentioned above?

**Comment by rchavarria** [comment]
When I started working on this some of these were true:

- I didn't know enough ESLint
- ESLint needed manual configuration for all that

Nowadays, configuring ESLint is much easier. I recently did it in my team. So, I prefer keeping this issue open, and I'll take care of this soon (within one week).

Depending on the number of errors found, it will generate some discussions, but I hope I can get most rules working without a huge effort.

**Comment by rchavarria** [comment]
I've been working on this on my own fork of the repo ([configure-eslint](https://github.com/rchavarria/xecmascript/tree/configure-eslint) branch)

It will have conflicts with other PRs, because some changes on `./package.json` (and that file on each exercise). So I don't want to open a PR yet. But, I'll open it when all PR are merged and I resolve conflicts.

There are a lot of ESLint rules to discuss :wink:

**Comment by matthewmorgan** [comment]
Hey @rchavarria, we've currently got 2 PRs open that affect the `package.json` files.  Hoping to get those merged so you can get this resolved also.  Thanks for being patient.

**Comment by rchavarria** [comment]
And both PR have files with conflicts 🤣 

I need to do some additional work on the ESLint config, so I can wait a little bit more. Don't worry.

**Comment by tejasbubane** [comment]
@rchavarria Did you figure this one out?

**Comment by matthewmorgan** [comment]
@tejasbubane @rchavarria Let's hold off on this one pending outcome of #412

**Comment by tejasbubane** [comment]
@matthewmorgan @rchavarria Can we proceed with the eslint integration now that the track migration is done? I am willing to lend a hand, let me know the approach.

**Comment by SleeplessByte** [comment]
Superseded by #681
