### ISSUE TITLE
Should ESLint configuration be in `package.json` file?

### ISSUE THREAD

**Issue by rchavarria** [exercism/javascript#441]
In the https://github.com/exercism/ecmascript track, ESLint config is in `package.json`. It has a reason, becasue that file is copied to all exercises, so it keeps a change that needs to be shared between all exercises in a single palce.

This track is a little bit different. Here, the config is outside `package.json`. #437 needs to add some ESLint configuration, to ignore some specific files, by adding a `.eslintignore` file.

Should ESLint configuration (`.eslintrc.json` and `.eslintignore`) be part of the `package.json` file?

**Comment by tejasbubane** [comment]
Since we don't copy `package.json` in this track, either way seems fine.
But just for the sake of consistency with the ecmascript track, and for us not to remember two different things, I think it will be better if we put in `package.json` itself.

**Comment by rchavarria** [comment]
It makes sense for me too. Any other thought @exercism/ecmascripts?

**Comment by matthewmorgan** [comment]
I agree with @tejasbubane

**Comment by rchavarria** [comment]
The discussion is more or less over, so I created a issue to do the actual work.

I'm going to close this issue. Anyway, if anyone has something to say, we'll be glad to listen.
