### ISSUE TITLE
Change installation link in exercise READMEs

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#447]
Each [exercise](https://github.com/exercism/javascript/tree/master/exercises) has a [README file with a setup link in it](https://github.com/exercism/javascript/blob/master/exercises/accumulate/README.md#setup).

The link points to http://exercism.io/languages/javascript/ but the setup instructions are in http://exercism.io/languages/javascript/installation. 

**Task:** Change the link to the correct installation link in README files of `all` exercises.

**Comment by Evalle** [comment]
Hey, @tejasbubane may I take a look at it?

**Comment by tejasbubane** [comment]
@Evalle Go for it!
