### ISSUE TITLE
Phone-number test cases are incorrect.

### ISSUE THREAD

**Issue by LyleCharlesScott** [exercism/javascript#449]
On the phone-number exercise in the ecmascript track, acceptable phone numbers are explained in the read.me to be of the format NXX NXX XXXX (with no spaces), where N is any digit from 2-9 (no zero or 1) and X is any digit from 0-9.

Four of the test cases use the phone number 123 456 7890, which does not fit the pattern. Changing those test cases to 223 456 7890 makes them compliant with the requirements. This is the way that the tests were previously written in the javascript track. The following updated test cases fixes the issue. 

```javascript
import PhoneNumber from './phone-number';

describe('PhoneNumber()', () => {
  test('cleans the number', () => {
    const phone = new PhoneNumber('(223) 456-7890');
    expect(phone.number()).toEqual('2234567890');
  });

  xtest('cleans numbers with dots', () => {
    const phone = new PhoneNumber('223.456.7890');
    expect(phone.number()).toEqual('2234567890');
  });

  xtest('cleans numbers with multiple spaces', () => {
    const phone = new PhoneNumber('223 456   7890   ');
    expect(phone.number()).toEqual('2234567890');
  });

  xtest('invalid when 9 digits', () => {
    const phone = new PhoneNumber('123456789');
    expect(phone.number()).toEqual(null);
  });

  xtest('invalid when 11 digits', () => {
    const phone = new PhoneNumber('21234567890');
    expect(phone.number()).toEqual(null);
  });

  xtest('valid when 11 digits and starting with 1', () => {
    const phone = new PhoneNumber('12234567890');
    expect(phone.number()).toEqual('2234567890');
  });

  xtest('invalid when 12 digits', () => {
    const phone = new PhoneNumber('321234567890');
    expect(phone.number()).toEqual(null);
  });

  xtest('invalid with letters', () => {
    const phone = new PhoneNumber('123-abc-7890');
    expect(phone.number()).toEqual(null);
  });

  xtest('invalid with punctuations', () => {
    const phone = new PhoneNumber('123-@:!-7890');
    expect(phone.number()).toEqual(null);
  });

  xtest('invalid with right number of digits but letters mixed in', () => {
    const phone = new PhoneNumber('1a2b3c4d5e6f7g8h9i0j');
    expect(phone.number()).toEqual(null);
  });
});
```

**Comment by tejasbubane** [comment]
@LyleCharlesScott Thanks for spotting this! We have the canonical test-cases [here](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) which I guess cover your point. I think we also need to change our implementation.

Would you be willing to send a PR to fix this?

**Comment by LyleCharlesScott** [comment]
Ah! I didn't see your reply until now. Sure, I'll set up a PR for it.

**Comment by tejasbubane** [comment]
Hi @LyleCharlesScott thanks! I can do a PR but that would deprive you of the credit. Here is a nice tutorial of how to create a PR https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github 

Give it a try. If you are facing some issues, just comment here and we can sort it out on slack chat.

**Comment by LyleCharlesScott** [comment]
K! I didn't realize I had to fork it, not just clone it. Pull request is up, with detailed documentation about what I did. 

The example.js file is broken though. The version from the deprecated ecmascript track doesn't have all of the functionality that the older one from the javascript track had. I think I'm going to try to update that now because it's a relatively simple refactor.

**Comment by LyleCharlesScott** [comment]
BTW Thanks so much for working with me on this and making me feel included. I love Exercism :-)

**Comment by tejasbubane** [comment]
Closed via https://github.com/exercism/javascript/pull/474
