### ISSUE TITLE
[Proposal] Consider using tape test runner

### ISSUE THREAD

**Issue by bennypowers** [exercism/javascript#450]
Tape supports esm and can be piped to a variety of reporters, which opens the door for further integrations (i.e. running test on the site)

https://github.com/substack/tape

**Comment by tejasbubane** [comment]
We prefer using `jest` since it is popular and familiar to our contributors. As I mentioned in #451, we cannot remove `babel`, I don't see any advantage in switching testing framework here. Please let me know what you think.

**Comment by bennypowers** [comment]
Before closing, consider the advantage of using [TAP-based reporters](https://github.com/substack/tape#pretty-reporters).

Thanks for your consideration.

**Comment by matthewmorgan** [comment]
@bennypowers I'm going to chime in late here and agree with @tejasbubane 

I'm not sure I see the advantage in switching the entire track over for what seems to be a matter of Coke vs. Pepsi.  If there were an inadequacy we needed to address, I could be convinced, but...

Please don't be discouraged from further comments and contributions!  We really do value comments and contributions.
