### ISSUE TITLE
Mistake in introduction to Armstrong Numbers

### ISSUE THREAD

**Issue by brunnock** [exercism/javascript#455]
*10 is not an Armstrong number, because 10 != 1^2 + 0^2 = 2*

1^2 + 0^2 = 1

**Comment by rpottsoh** [comment]
PR #456 fixes this problem.  However, that PR fixes all the READMEs that are out of date in this track.  They may opt to go about fixing this issue another way.  Their call.

Thanks for spotting this!

**Comment by tejasbubane** [comment]
Thanks for spotting this! Mind sending a quick PR to fix it? 

The file you need to change is [here](https://github.com/exercism/javascript/blob/master/exercises/armstrong-numbers/README.md). And correct README for reference is [here](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/description.md).

**Comment by tejasbubane** [comment]
Sorry @rpottsoh did not see your comment. Thanks for the PR - LGTM - will wait for response from other maintainers.

**Comment by tejasbubane** [comment]
This has been fixed in #456 - should be live with the next deploy.
