### ISSUE TITLE
Upgrade Jest

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#460]
Upgrade Jest to latest version: https://www.npmjs.com/package/jest

Steps:

1. Change the `package.json` in root of this project.
1. Run `npm install` so that it updates `package-lock.json`.
1. Now each exercise has `package.json`, but you don't need to update all of them manually! Run `make test` to copy updated `package.json` from root to all exercise directories `exercises/<name>/package.json` and run the tests.
1. Commit the changes and submit a PR 🎉

**Comment by iagocavalcante** [comment]
I'll send the PR.
