### ISSUE TITLE
hello-world: URL to Installation instructions not linked.

### ISSUE THREAD

**Issue by Insti** [exercism/javascript#467]
In the readme for hello-world the URL for the installation instructions under 'setup' is not a link.

https://exercism.io/tracks/javascript/installation

(it is here on github, but not on the exercism.io page.)

**Comment by tejasbubane** [comment]
> (it is here on github, but not on the exercism.io page.)

Which exercism.io page are you referring to here?



> URL for the installation instructions under 'setup' is not a link.

I guess you mean it should be changed to `[]()` format?

**Comment by Insti** [comment]
> Which exercism.io page are you referring to here?

The readme page that one sees when one clicks on the hello-world exercise as a logged in student.

Probably this one: 

https://github.com/exercism/javascript/blob/master/exercises/hello-world/README.md

>  I guess you mean it should be changed to `[]()` format?

That's it.

**Comment by Insti** [comment]
You're a hero @tejasbubane 
thanks :heart:
