### ISSUE TITLE
Twelve days is out of sync with specification

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/javascript#477]
The specification for twelve days has been change to correct a punctuation issue.

https://github.com/exercism/problem-specifications/blob/84aa47979df7f526bdcb777cacc2c2cc9647dcaa/exercises/twelve-days/description.md

**Comment by matthewmorgan** [comment]
Hi @PatrickMcSweeny !

Do you want to put in a PR for this, or just bringing it to our attention?
