### ISSUE TITLE
What type of JS module pattern is used in exercism?

### ISSUE THREAD

**Issue by mspanish** [exercism/javascript#479]
This sounds like a ridiculous question, but I've never been all that fond of modules, and mostly avoided them. But in the first few exercises on Exercism, I found the modules to be very nice - and it would certainly help my coding to use this style more. What specific pattern is this, or does anybody have a URL where I can do more practice writing these kind of modules, or reading reference materials about them? Thanks!

**Comment by matthewmorgan** [comment]
@mspanish I'm glad to hear you're enjoying the track!

Exercism's JavaScript track uses CommonJS modules.  Support for CommonJS is baked in to Node JS.  However, if you want to package together modules into code for the browser, you will need to include a tool such as Webpack or Browserify in your build process.

Here's a blog post about CommonJS and how `require` works: https://blog.risingstack.com/node-js-at-scale-module-system-commonjs-require/

Please feel free to ask if you have more questions.

**Comment by mspanish** [comment]
Thanks very much 👍
