### ISSUE TITLE
linked-list requirements incomplete

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/javascript#480]
from https://github.com/exercism/exercism.io/issues/3697

Submitted by @bennypowers

It's possible to pass the linked-list tests for JS/ES like so:

```javascript
const List = Array;
List.prototype.count = function () { return this.length; };
List.prototype.delete = function (value) {
  return this.indexOf(value) !== -1
    ? this.splice(this.indexOf(value), 1)
    : this;
};

export default List;
```

It seems to me that this object doesn't satisfy the true definition of linked-list, although it does pass the tests.

Please correct me if I'm wrong.

**Comment by matthewmorgan** [comment]
@bennypowers you are indeed right about this: one can pass this test by extending the native Array object.  We do have other exercises that have this same failing, and in the README we challenge the student to implement a solution _without_ the native type.  "Strain" and "Accumulate" are such exercises.

So the question is:
1. Challenge the student to implement this solution without the native type?
2. Change the method names?  Note that in the absence of (1), the student could just wrap the native methods.
3. Add tests that traverse the list?
4. ?

I don't support (2).  It seems awkward to force the student to implement something that purposely abandons the semantics of a traditional linked list.

I'd be most in favor of (1).  It would allow the student to submit a "green" solution that uses `Array` in some way, then challenge themselves to work with more basic types.

@bennypowers did you have a proposed solution in mind when you file this issue?

**Comment by bennypowers** [comment]
I'd prefer option 4, since my usual MO is to write in TDD style acc'd to the spec provided.

**Comment by matthewmorgan** [comment]
Option (4) is not defined...do you have a proposal?

**Comment by bennypowers** [comment]
apologies, I meant option 3

**Comment by matthewmorgan** [comment]
Let's see if we can get some consensus from the maintainers, then we can take action.

Thanks for pointing this out!

@exercism/ecmascripts would you all mind weighing in on this one?

**Comment by rchavarria** [comment]
I would vote at least for option (1): encourage not cheating, and implement List on student's own.

I don't see too much value on option (2). It can be easily cheated. I'm not sure, but I swear there was a discussion about method names. Maybe it was method names across languages: some propose `push`, other `add`, `append`,... Or maybe `push/pop` reminds people to queues instead of lists. Not sure, I'm talking by memory, I didn't check anything.

Option 3 seems reasonable. It could be the last test. Something like:

> solution does not inherit/is based on native implementations

Or, tests could check that the `List` object has no some native methods not required by specs.

**Comment by bennypowers** [comment]
> solution does not inherit/is based on native implementations

but where's the linked part of the list? shouldn't the interface specify that each node must link explicitly to the previous or next? (or null in case of 0 and last)?

**Comment by malydok** [comment]
Solution **3** is the only reasonable one in my opinion as well. Upto this very task all the tests were written in a such a way that you couldn't possibly cheat. Adding tests for proper `Node` creation should solve the problem, for example:

```
var list = new LinkedList();
list.push(10);
list.push(20);
expect(list.first.value).toBe(10);
expect(list.first.next).toEqual(list.last);
expect(list.last.previous).toEqual(list.first);
```

Of course then the task assumes the names of attributes in `List` and `Node`, but that's not really a big issue, all the tasks assume some naming conventions.

**Comment by bennypowers** [comment]
I agree @malydok. Maybe throw in an `isObject` or `instanceof Node` test to make it clear to students.

**Comment by matthewmorgan** [comment]
@bennypowers would you care to make a PR for this?  Your help would be welcome.

**Comment by bennypowers** [comment]
Would be happy to, when I get a free moment. 

It seems to me that push should create a `new Node`

**Comment by bennypowers** [comment]
Apologies to followers. I am interested in moving this forward but give it a lower priority at the moment. I estimate I'll be able to seriously work on this within 2-3 mo.

**Comment by matthewmorgan** [comment]
Fair enough @bennypowers .  Let's close it until that time, so it doesn't linger unresolved.  Thanks!
