### ISSUE TITLE
"unlocked_by" should not be null for non-core exercises

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/javascript#483]
@exercism/ecmascripts correct me if I'm wrong here, but my understanding of the new setup is that exercises should either be `core: true` or have a non-null `unlocked_by` value.

If I am right, then we have 6 exercises currently that are `core: false` and `unlocked_by: null` that we need to assign `unlocked_by` parents to.

?

I've entered this same issue for the EcmaScript track.

**Comment by rchavarria** [comment]
Replied on https://github.com/exercism/ecmascript/issues/387

**Comment by tejasbubane** [comment]
Closing this one as per discussion in https://github.com/exercism/ecmascript/issues/387
