### ISSUE TITLE
Suggested improvements to beer song exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/javascript#489]
Related to the [99 Bottles of OOP](https://www.sandimetz.com/99bottles/) book, we have a repository containing all the available BeerSong exercises from Exercism.

One reader, @dcarral, submitted a whole host of little fixes and improvements, that I'd like to bring into Exercism where appropriate.

Here are the fixes for the JavaScript exercise:

> * Improve JavaScript test suite by modifying expectations and adding a full lyrics test.
> * Adds empty implementation file in JavaScript: this way participants achieve failing test ('BeerSong is not a constructor') instead of module loading error when trying to require a non-existing file.

The changes are in this file:
https://github.com/dcarral/99bottles-polyglot/pull/11/files#diff-dfaa7cd627b791e136aaca588bee0772

I can't speak to the JavaScript aspect of these, but I think they're worth considering.

**Comment by rchavarria** [comment]
Expectations look much much better, the descriptions are really improved. I agree on including those changes on the exercise.

I have my doubts about them empty implementation file. For the first exercises, the track provides a scheleton of the implementation, so users should know how to start creating implementation files (stub files?) on their own (providing stub files was discussed some time ago on #424)

**Comment by benfletcher** [comment]
I wanted to add a vote in favor of adding implementation starter file to each exercise, would be a great QOL helper for experienced programmers and prevent a stumbling block for beginners.

I'd be happy to implement this and/or the other changes if desired.

**Comment by matthewmorgan** [comment]
@benfletcher @rchavarria @kytrinyx I think it could be valuable to add this case-by-case to certain exercises.  I am _not_ in favor of adding stubs to _all_ exercises, but that's just because there are so many different ways to implement most of the solutions in JavaScript.  I think stubs have value in two contexts:

1. Early in the track to help people who are new to the language, or to programming in general.
2. For specific problems with arcane or tricky APIs.

That's my 2 cents.

**Comment by kytrinyx** [comment]
I am also not in favor of adding stubs to all the exercises for the reasons that @matthewmorgan mentions.

**Comment by matthewmorgan** [comment]
wontfix per #556.
