### ISSUE TITLE
Bowling example and spec file do not implement all canonical tests

### ISSUE THREAD

**Issue by danielj-jordan** [exercism/javascript#496]
The bowling example does not implement the Roll(pins:int) operation as desribed in the exercise requirements.  Instead it accepts an array of rolls in the constructor.   Also there are numerous discrepancies with the [canonical spec](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json) file including the following tests which are missing:
	- bonus roll after a strike in the last frame cannot score more than 10 points
	- second bonus roll after a strike in the last frame cannot score more than 10 points
     -    cannot roll after bonus roll for spare
	- cannot roll after bonus rolls for strike

I fixed this on the deprecated javascript tract.  I volunteer to fix it again.

**Comment by matthewmorgan** [comment]
@danielj-jordan welcome back...we'd love to have your help  again!
