### ISSUE TITLE
Change two-fer exercise to use named exports

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#503]
Issue: https://github.com/exercism/javascript/issues/436

You are expected to change the export from default to named. Files to be changed: [code](https://github.com/exercism/javascript/blob/d3388886b794e75a0352d672bcd31fa6cf516d45/exercises/two-fer/example.js#L1) and [test](https://github.com/exercism/javascript/blob/d3388886b794e75a0352d672bcd31fa6cf516d45/exercises/two-fer/two-fer.spec.js#L1)

Refer to the PRs linked to above issue and the [official docs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Description) as required.

**Comment by ivanuy** [comment]
I would like to work on this

**Comment by tejasbubane** [comment]
@ivanuy This has been fixed. Please feel free to pick other issues - especially https://github.com/exercism/javascript/issues/480 where there are lot of exercises to be fixed - you can pick any exercise and send a PR. Thanks.
