### ISSUE TITLE
THis is more of a question about Jasmine??

### ISSUE THREAD

**Issue by AnnahGerletti** [exercism/javascript#505]
I am new to using Jasmine, I find when something breaks in the code Jasmine does not always out-put an error to my terminal. Why is this. I just get the same line returned.

like this:
```
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master)
```
The first line is good with a green arrow, but the next three are the responses to running the command.
Nothing happens. No Output.

**Comment by joelwallis** [comment]
Question previously asked on exercism/exercism.io#3732

**Comment by joelwallis** [comment]
Hi @AnnahGerletti,

I'm one of the co-maintainers of the JavaScript track. This Jasmine behavior definitely isn't normal. It's supposed to show something like this:

```
$ jasmine ./hello-world.spec.js
Started
.


1 spec, 0 failures
Finished in 0.009 seconds
```

Which operating system are you using? Also, can you provide more information about your environment? Run the command below and paste the output here:

```
exercism version; node --version; jasmine -v
```

**Comment by AnnahGerletti** [comment]
Hello, 

I am running on a MacOS, using Zsh as my CLI, writing code in VSCode. Is that what you wanted to know. 

here is the results to the comand
```
➜  rna-transcription git:(master) exercism version; node --version; jasmine -v
No help topic for 'version'
v9.4.0
jasmine v3.0.0
jasmine-core v3.0.0
➜  rna-transcription git:(master) 
```

**Comment by AnnahGerletti** [comment]
There will be times when I do see something like this:
```
Randomized with seed 53901
Started
....F**

Failures:
1) toRna() transcribes all dna nucleotides to their rna complements
  Message:
    Expected undefined to equal 'UGCACCAGAAUU'.
  Stack:
    Error: Expected undefined to equal 'UGCACCAGAAUU'.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/annahgerletti/exercism/javascript/rna-transcription/rna-transcription.spec.js:23:8)
        at <Jasmine>
Pending:
```
However if I change the code in VScode and then try to run the test again, I won't get any kind of error message which is difficult to debug. I was just wondering are there steps when using Jasmine that I need to keep in mind? Forexple can't run partial code, or no comment? things like that.

**Comment by joelwallis** [comment]
@AnnahGerletti there's no step to follow before running `jasmine`. You should be able to see its output right after running the command. It doesn't seem like a broken output to me. Can you share an example of an output that doesn't get you information about your solution? Posting your solution alongside the given output would be very helpful.

**Comment by AnnahGerletti** [comment]
Sure here is my current work, its not finished. I am working on the 4th JS assignment DNA to RNA. 
```
var Rna = {
  'C': 'G',
  'G': 'C',
  'A': 'U',
  'T': 'A'
}

var DnaTranscriber = function () {
}

DnaTranscriber.prototype.toRna = function (input) {
  var nucleotides = input.split('')
  nucleotides.map(input) {

  }
  return Rna[input]
}

module.exports = DnaTranscriber
```
I get nothing in the terminal when I run Jasmine. 
```
➜  rna-transcription git:(master) ✗ jasmine rna-transcription.spec.js
➜  rna-transcription git:(master) ✗
```

**Comment by rchavarria** [comment]
Not sure, but I think there is a syntax error in the code. Instead of `nucleotides.map(input) {`, would you mind to use *old* JavaScript? I mean, `function` and everything else. Kind of:

```
nucleotides.map(function (input) {
  // use input to do something
});
```

In fact, you may want to write that in ES2015 syntax:

```
nucleotides.map(input => {
  // use input to do something
});
```

**Comment by tejasbubane** [comment]
Looks like `jasmine v3.0.0` just fails on a syntax error without reporting anything - although I cannot find a relevant github issue in jasmine repo, I can confirm this by running above code.

The latest jasmine `v3.1.0` does the right thing - reports proper error.

@AnnahGerletti Can you update jasmine to the newer version and confirm?

**Comment by AnnahGerletti** [comment]
How do I upgrade Jasmin? the npm docs tell me to run an `npm install` but there is no package.json.

Isn't there a `jasmine upgrade` command?

**Comment by AnnahGerletti** [comment]
Never mind I used `npm upgrade -g jasmine` this seemed to work.

**Comment by tejasbubane** [comment]
For the javascript track we recommend installing Jasmine globally. That is
how you are able to access `jasmine` command.

 Running `npm install -g jasime` should update it I guess.

**Comment by AnnahGerletti** [comment]
getting proper errors now. Thanks for all the help.

**Comment by tejasbubane** [comment]
Awesome! Thanks for being patient with the issue.

**Comment by AnnahGerletti** [comment]
You Guess, that sounds like you know of a better way to do it?? 

 Running `npm install -g jasime` should update it I guess.

**Comment by joelwallis** [comment]
@AnnahGerletti updating it globally is just a matter of running `npm i -g jasmine`. You're good to go now! :-)

**Comment by AnnahGerletti** [comment]
Yay!! thanks for all the help. Let's close this issue.
