### ISSUE TITLE
secret-handshake should test using dec values

### ISSUE THREAD

**Issue by PSalant726** [exercism/javascript#509]
The `secret-handshake.spec.js` file should pass the appropriate dec value to the `SecretHandshake` constructor, per the prompt:
```
Given a decimal number, convert it to the appropriate sequence of events for a secret handshake.

Here's a couple of examples:

Given the input 3, the function would return the array ["wink", "double blink"] because 3 is 11 in binary.

Given the input 19, the function would return the array ["double blink", "wink"] because 19 is 10011 in binary. Notice that the addition of 16 (10000 in binary) has caused the array to be reversed.
```
However, the test file passes a hexadecimal value to the `SecretHandshake` constructor for each test, for example:
```js
test('binary 11111 (hexadecimal 0x1F) is jump, close your eyes, double blink, and wink', () => {
    const handshake = new SecretHandshake(0x1F);
    expect(handshake.commands()).toEqual(['jump', 'close your eyes', 'double blink', 'wink']);
  });
```
This creates an issue because two-way conversions from hex <--> bin is not possible in JS:
```js
parseInt(11111, 2).toString(16) === "1f"
parseInt(0x1F, 16).toString(2) === "110001"
```
The spec file should be modified so that conversions to the expected binary values can occur, like:
```js
test('binary 11111 (decimal 31) is jump, close your eyes, double blink, and wink', () => {
    const handshake = new SecretHandshake(31);
    expect(handshake.commands()).toEqual(['jump', 'close your eyes', 'double blink', 'wink']);
  });
```

**Comment by PSalant726** [comment]
I can open a PR to address this issue, but I thought it would be worthwhile to discuss the spec file here first, in case I'm missing something.

**Comment by matthewmorgan** [comment]
@PSalant726  I don't think there's anything to discuss!  How did this happen?  Not sure, but definitely `problem-specifications` seeks decimal inputs, not hexadecimal inputs.

Please proceed with your PR, that would be welcome :)
