### ISSUE TITLE
Correct simple-cipher linting issues

### ISSUE THREAD

**Issue by cybernetck** [exercism/javascript#521]
I'd like to correct simple-cipher linting issues.

**Comment by ajomadlabs** [comment]
@cybernetck There is already an existing issue regarding the exercises thats need to corrected. I guess you can look over the link given below
[Linting Issue Checklist](https://github.com/exercism/javascript/issues/399)

**Comment by matthewmorgan** [comment]
@ajomadlabs is correct to point out #399.

@cybernetck what we'd like you to do is open an empty PR with a title like "Dibs-- fix linting issues for simple-cipher" to make your intentions visible.  

Thanks!
