### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#525]
We have quite a few things going on in the CI and elsewhere. Now we also have ESLint. A new contributor [here](https://github.com/exercism/javascript/issues/480#issuecomment-431656972) was quite confused since the [contributing guidelines right now](https://github.com/exercism/javascript/blob/377a39af3165bc3dd097878f6bd9fc92aead8b52/CONTRIBUTING.md) point to [this repo](https://github.com/exercism/docs) which is quite generic and might be confusing for newcomers.

I suggest we add our own `CONTRIBUTING.md` which documents things like:
* The contributing guidelines - call dibs -> fix -> push -> create PR -> wait for review -> merged.
* All the checks in CI explained along with things like how to handle most common errors (eg. package.json not matching, eslint failures, etc)
* ESLint rules and exceptions

Some more things can be added as required.

**Comment by adamxtokyo** [comment]
[This issue](https://github.com/exercism/javascript/issues/502) could go into the common errors section, as I imagine more people will run into it 👍
