### ISSUE TITLE
Inconsistent module use

### ISSUE THREAD

**Issue by gavinhenderson** [exercism/javascript#544]
This issue was originally brought up in #543 by @alexch. 

The module decleration is inconsistent in terms of what is expected from the module when it is required. Sometimes it expects an object with functions and fields. Other times it expects the module to be just a function. Lastly, sometimes it expects the module to only contain one function but the module itself is not the function.

Sometimes it makes sense to have different things but in a lot of cases it doesnt.

# Examples
These examples all could be used in the same way but aren't

### Module is Class
In the [all-your-base](https://github.com/exercism/javascript/tree/master/exercises/all-your-base) challenge the module expects an object with only one function. The object stores nothing at all besides the function. The funciton only uses data from the parameters given to it. Subsequently in the tests it is initialised once and then just used as a store for a single function. 
```javascript
const Converter = function () { };
```

### Module is Function
In the [accumulate](https://github.com/exercism/javascript/tree/master/exercises/accumulate) challenge the module is expected to be a function.
```javascript
module.exports = function (list, accumulator) {
```

### Module has function
In the [acronym](https://github.com/exercism/javascript/tree/master/exercises/acronym) challenge the module expects to include the function 'parse'. It only expects a single function and nothing else.
```javascript
module.exports = {
  parse: function (phrase) {
```

**Comment by gavinhenderson** [comment]
Ah, I see that the conclusion was to keep the first challenges consitent with each other, even if a class has one function, which I agree with.

However, all the challenges I mentioned in my issue are past the first 10 challenges. After the first challenges would it not be better to use the most appropriate module use rather than forcing people to use inappropriate classes in the sake of consistency?

**Comment by matthewmorgan** [comment]
Closing as wontfix per #556.
