### ISSUE TITLE
Pangram exercise needs to decide whether it involves non-ASCII characters or not

### ISSUE THREAD

**Issue by MadEmperorYuri** [exercism/javascript#551]
http://exercism.io/exercises/javascript/pangram/readme says "Input will not contain non-ASCII symbols."

But http://exercism.io/exercises/javascript/pangram/test-suite says

```javascript
xit('pangram with non-ascii characters', function ()  {
  var pangram = new Pangram('Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.');
  expect(pangram.isPangram()).toBe(true);
});
```

One of the two must go, but which? I vote to keep the non-ASCII characters. Any solution that can deal with punctuation will probably deal with non-ASCII characters just fine, and the extra passing test is more rewarding.

**Comment by tejasbubane** [comment]
@MadEmperorYuri Thanks for catching this! The README and test suite are definitely out of sync. Exercism has a repository for problem specifications and we prefer to follow that. For `pangram` here is the [Readme](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/description.md) and [test specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json).

So the test cases are the ones that should be changed. There are a couple extra cases that I see in the test specifications file as well. So the task is to remove the non-ASCII test case and make the test cases in sync with the [spec file](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json).

Would you be willing to send a PR for this?

**Comment by aadityakulkarni** [comment]
Hi @tejasbubane I have created a PR for this task.
