### ISSUE TITLE
Consider using the Codacy code review tool

### ISSUE THREAD

**Issue by xarxziux** [exercism/javascript#559]
[Codacy](https://www.codacy.com/) is an automated code review tool that is free for open source projects.  It provides automated linting and security checks with a comprehensive dashboard that goes into detail on the issues found.  This review is automatically triggered on every commit.

With the current drive towards cleaning up the linting errors in issue #480, setting up the project on Codacy would help towards that, I feel.  One minor issue is that while Codacy supports ESLint, it doesn't appear to support having the config setting embedded inside package.json.  In order to prepare this repo for Codacy, this would need to be moved to a separate config file.

This is a simple change to make, and the process of singing up for Codacy is pretty straightforward too as it has good integration with GitHub.  How would you feel about setting this up?  Do you think this would be a worthwhile change?

**Comment by SleeplessByte** [comment]
As far as I'm concerned, they don't offer anything on top of `eslint`, unlike codeclimate, which is also free for open source.

Let's close for now and revisit if we have to.
