### ISSUE TITLE
Luhn Exercise

### ISSUE THREAD

**Issue by jsmith0684** [exercism/javascript#578]
Test 3 of the Luhn test suite with description 'valid Canadian SIN' appears to be incorrect.

Test input: '046 454 286'
Translated: 0 + 4 + 12 - 9 + 4 + 10 - 9 + 4 + 4 + 8 + 12 - 9 = 31
31 isn't evenly divisible by 10 therefore the result should be false not true.

**Comment by gabriel376** [comment]
Can I take this one ?

**Comment by tejasbubane** [comment]
@gabriel376 Yes. I don't think @jsmith0684 worked on this one.
