### ISSUE TITLE
package.json script to run next test

### ISSUE THREAD

**Issue by sheadscott** [exercism/javascript#583]
I wrote this script to automate running the next test:

`"nexttest": "gsed -i -e '0,/xtest/s/xtest/test/' *.spec.js && jest --no-cache ./*",` 

gsed is the Mac OSX version of gnu-sed and can be installed with `brew install gnu-sed`. The default OSX version of sed uses a different syntax. 

The command finds the first instance of "xtest" and changes it to "test" and then runs the jest command. This same syntax should work with the syntax on Linux by replacing "gsed" with "sed". If this is something that can be rolled into package.json, I can write a version with the default OSX syntax.

**Comment by tejasbubane** [comment]
Ideally I would like **any** command to behave similarly on all platforms (OSX, Linux and Windows). 

We would have to:

* Write some code to use either `sed/gsed` based on platforms - I don't even know if there is equivalent on Windows. 
* Make changes in the [documentation](https://exercism.io/tracks/javascript/tests) asking users to install `sed/gsed/<windows-equivalent>`

I understand automation is cool, but in this case my feeling is it is not worth doing all this. The instructions are pretty simple especially for users who are new to programming altogether. I will keep this issue open for thoughts from other maintainers.

**Comment by matthewmorgan** [comment]
@sheadscott I have to agree with @tejasbubane on this.  We really appreciate the thought and the initiative to improve the project, but we'd like to see things evolve in the direction of _more_ consistency between platforms, and _less_ required setup.  

I am concerned that this would take us in the other direction on both points, unless I misunderstand.

**Comment by sheadscott** [comment]
@matthewmorgan and @tejasbubane I agree that it would need to be consistent on all platforms. I mostly just wanted to post this somewhere in case anyone can use it and see if the concept would be something the maintainers would be interested in.

I can imagine writing this as a node script that could possibly go in the .exercism folder or could be it's own hidden file.

**Comment by tejasbubane** [comment]
Closing this since both maintainers agreed this is not required. Others are free to use the script from this issue - but we choose to not recommend it via adding hidden file, etc. 

Please don't be discouraged by this - we appreciate your interest and would like to hear more on ways in which we can improve exercism. Thanks.
