### ISSUE TITLE
Suggestion: prefer eslint syntax over style

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#589]
With [more](https://github.com/prettier/prettier) and [more](https://github.com/xojs/xo) tools becoming available to automatically format the code base to a certain set of style rules (and [more comprehensive](https://github.com/prettier/prettier-eslint/issues/101) than `eslint --fix`, I'm also more inclined to stop teaching style preference, as indicated by mentor notes, mentor guidance docs and discussions on slack.

## The current state
Currently, the javavscript `package.json` sets a _very restrictive_ code style (`airbnb`) and I *don't* think this:
- helps the student understand the language
- helps the student get fluent in a language
- helps the mentor mentoring as downloading exercises can result in wibbly wobblies all over the place

We don't instruct or enforce these rules (https://github.com/exercism/javascript/issues/44#issuecomment-416760562) strictly, but I seem them in mentoring comments and most IDE's will run these _automagically_ if present.

## Recommendation
I therefore recommend to drop down to [eslint:recommend](eslint:recommended"](https://eslint.org/docs/rules/)) or if we must have a non-company style guide, use [standard](https://github.com/standard/eslint-config-standard) with semicolon rules disabled (people should decide about ASI themselves -- I don't think pushing people who know about ASI helps anyone, and TS doesn't have them either).

If this is something we want, I think doing it sooner rather than later is good and will speed up #480 greatly. The eslintignore list is still quite long and I don't think tháts particularly helpful.

As a final note, I think we should _better_ communicate to the students to run `npm/yarn install` and then `npm/yarn test`. I also suggest running `test` followed by `lint` so that someone is only bugged once the test succeeds, instead of using a `"pretest": "lint"`:

```json
{ 
  "scripts": {
    "test": "test:jest && test:lint",
    "test:jest": "...",
    "test:lint": "..."
   }
}
```

**Comment by tejasbubane** [comment]
> Currently, the javavscript package.json sets a very restrictive code style (airbnb) and I don't think this:
> * helps the student understand the language
> 
> * helps the student get fluent in a language
> 
> * helps the mentor mentoring as downloading exercises can result in wibbly wobblies all over the place

The eslint config is not for students. It is for contributors contributing to this track repo. We do not enforce **any** style restriction on students.

**Comment by SleeplessByte** [comment]
I know that _we_ don't, but that's not how IDE's work. VS Code for example will pick up the eslint configuration _by default_ if the plugin is active. Atom en Webstorm too!

Evidently, we should change something as mentors áre referring to it in their comments :)
@tejasbubane I don't know of a super smart way to do this right; running `eslint:recommend` for students is actually something I would prefer since it helps you fix actual bugs --

**Comment by tejasbubane** [comment]
Ok. Some very valid points that I completely took for granted:

> I know that _we_ don't, but that's not how IDE's work.

I did not realize that we give the eslint config in [exercises](https://github.com/exercism/javascript/blob/master/exercises/accumulate/package.json#L59-L77) which students download. I assumed we only validate it from [main package.json file](https://github.com/exercism/javascript/blob/master/package.json)

> Evidently, we should change something as mentors áre referring to it in their comments :)

I did not know this as well. Looks like we definitely should do something about this.

I am in the favor of not recommending anything to students - only use it for CI in our repo. For mentors, put a mentor note regarding the same. What do you think?

**Comment by tejasbubane** [comment]
> I am in the favor of not recommending anything to students - only use it for CI in our repo. For mentors, put a mentor note regarding the same. What do you think?

This is because JS does not have a standard formatting tool (you mentioned the same in previous comment). Had it been [golang](https://golang.org/cmd/gofmt/) or [elixir](https://hexdocs.pm/mix/master/Mix.Tasks.Format.html), it would be good to recommend.

Having said that I am OK with using `eslint:recommend` as well. But I would certainly put up a mentor note to atleast not make it a requirement for students (it is fine to subtly suggest, but not making it a requirement for approving solutions).

**Comment by SleeplessByte** [comment]
I'm happy to actually strip _all_ style items left in `eslint:recommend` btw! We are definitely in sync on reasoning and I agree with everything you say.

**Comment by SleeplessByte** [comment]
@tejasbubane I think we can choose a permutation one of these:
- use a track-level eslint configuration on something "strict", `eslint:recommended` including style rules,
- drop exercise-`package.json` eslint config and dependencies. This will _not_ disable eslint in `travis` in the exercises folders, if I'm right.
- change exercise-`package.json` eslint and dependencies to use `eslint:recommended` or even looser.
