### ISSUE TITLE
I don't understand how to use spec.js

### ISSUE THREAD

**Issue by NobbZ** [exercism/javascript#602]
@chrismjx commented on [Tue Feb 05 2019](https://github.com/exercism/cli/issues/804)

I just downloaded leap.spec.js for the javasript track, and my question is a very newbie "How do I use this?"

The first line appears to be importing a file from somewhere. The describe block seems to be describing the gist of the test? The rest of the stuff starting with "xtest" is what I'm really confused by. What is all of this? Is it just showing what the test scenarios should be?

---

@NobbZ commented on [Wed Feb 06 2019](https://github.com/exercism/cli/issues/804#issuecomment-460953826)

Hello @chrismjx, your issue is not related to the `exercism`-CLI, therefore I'll move it to the appropriate place.

**Comment by SleeplessByte** [comment]
@NobbZ thank you for moving!

@chrismjx I understand your question. 
Both on [the track](https://exercism.io/my/tracks/javascript) and `hello-world` you can find the instructions and link to [installation](https://exercism.io/tracks/javascript/installation) followed by [running the tests](https://exercism.io/tracks/javascript/tests).

> **Understanding Skip Tests**
> The skip method instructs the test suite to not run a test, this function could be used also under the aliases: it.skip(name, fn) or xit(name, fn) or xtest(name, fn)
>
> Why they are skipped ? So as to enable users to concentrate on one test at a time and enable one by one as they evolve the solution.
>
> How to enable them ? Change xtest to test.

Please take the time to follow the instructions.
