### ISSUE TITLE
Create exercise versioning policy based on Haskell track

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#628]
Exercism tracking issue: https://github.com/exercism/exercism/issues/4786
- haskell: https://github.com/exercism/haskell/pull/717/files#diff-c6795c529069232683d979cd4239c219R2
- ocaml: https://github.com/exercism/ocaml/issues/283
- javascript: https://github.com/exercism/javascript/issues/628

**Note**: This is not the same as https://github.com/exercism/exercism/issues/4266 which removed tracking versions from the user code.

## Proposed implementation for JavaScript

In `package.json` change the `version` number to match the `x.y.z` of [test data versioning](https://github.com/exercism/problem-specifications#test-data-versioning), and add `.q` which we always increment if a change is made without a sync (new test data): `x.y.z.q`.

**Comment by tejasbubane** [comment]
@SleeplessByte For now I suggest not adding extra `.q` and matching with test data versions. This is ofcourse assuming that our test will match test data exactly and we won't be needing any extra tests.

**Comment by tejasbubane** [comment]
Sorry for not being clear with the issue description. Better late than never if anyone else ends up here.

The issue here is not all exercises in this track are in sync with problem specifications. Some (if not most) lag behind and miss some tests or have old version of tests. We need to take this case by case basis and do the following:

* If all tests match, just update version number and we should be good.
* If tests don't match, make the changes required to match them and then update the version number.

I would expect separate PRs with a few exercises - not more than 3-4 in one PR so that it is easy to review.

**Comment by SleeplessByte** [comment]
@tejasbubane yep! I'll make a checklist too.

**Comment by smb26** [comment]
Can I have it please? 😄

**Comment by SleeplessByte** [comment]
@smb26 ❤️ of course. Could you start by opening another issue with at least the ones you're doing but preferably all the exercises as a checkbox (like I did with  https://github.com/exercism/javascript/issues/600) and name it:

```markdown
#Checklist: add exercise versioning
```

Note the steps are listed here: https://github.com/exercism/javascript/issues/628#issuecomment-469569417

**Comment by SleeplessByte** [comment]
@tejasbubane any update on the makefile change to remove the version / replace it with 0.0.0 when doing the integrity check (when running `make test-travis` as well as merging the current version into the copy when running `make`?

**Comment by sshine** [comment]
Haskell's versioning policy was decided in exercism/haskell#522, implemented in exercism/haskell#523 and documented in exercism/haskell#716. In particular, the main benefit of having a fourth serial version number is that you can track changes to any part of the exercise files given to a user.

Having only the canonical version means you can keep the exercise up-to-date with canonical tests.

**Comment by SleeplessByte** [comment]
Thank you for these links @sshine !

**Comment by tejasbubane** [comment]
I was planning to add versions to `package.json` files but I guess there are more options being discussed in https://github.com/exercism/discussions/issues/239. We will wait for a decision to be made over there.

**Comment by SleeplessByte** [comment]
I've started adding versions, because I can use the package.json in the test runner. 
See https://ooew0.csb.app/javascript for status.

Let's revisit this once that discussion is resolved, but use package.json for now. It will be trivial to move the version to _whereever_.

**Comment by SleeplessByte** [comment]
We've dropped versions from canonical problem specs, so they don't make sense anymore in the context of this issue.
