### ISSUE TITLE
linked-list definition of "head" and "tail"

### ISSUE THREAD

**Issue by mp0wr** [exercism/javascript#629]
the notion of "head" and "tail" seem to be backwards in the `example.js`.
I'd expect "back" to correspond to "tail" and "front" to correspond to "head", like [this article](https://hackernoon.com/the-little-guide-of-linked-list-in-javascript-9daf89b63b54).

the example works and tests, but it seems conceptually misleading, imo.

README:

> * `push` (*insert value at back*);

example.js:

```javascript
  push(value) {
    if (this.head) {
      const newHead = new Element(value);
      newHead.next = this.head;
      this.head.prev = newHead;
      this.head = newHead;
    } else {
      this.head = new Element(value);
      this.tail = this.head;
    }
  }
```

**Comment by SleeplessByte** [comment]
Hi there,

I probably agree with you, despite me writing the notes [like this](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/linked-list/mentoring.md) as that matched the example more. I think the original author who created this exercise from the spec determined that the last pushed element should always be `head`, so the array's head is at it's end.

We'll accept a PR here + the website-copy mentoring notes.

**Comment by mp0wr** [comment]
Working on it.

@SleeplessByte,
Ok to update the code example for this like this?
*The mentor notes for linked-list seem out of date. Little things like `Element` is expected by test spec, `Node` is referenced in the mentor copy.*

Node constructor arguments: `constructor({ value, next, prev }) {...`
Element constructor args: `(value)`

**Comment by SleeplessByte** [comment]
The [tests](https://github.com/exercism/javascript/blob/master/exercises/linked-list/linked-list.spec.js) actually don't expect `Element`. I would open a PR here (`exercism/javascript`) with the following text:

    This PR updates the `example.js` code to be more reasonable. The `head` of the 
    list is now also the front, and the `tail` of the list is now also the back. 

    This matches the explanation in [this article](https://github.com/exercism/javascript/blob/master/exercises/linked-list/linked-list.spec.js) 
    and the readme.md of this exercise.

Only change `example.js`.

**Comment by mp0wr** [comment]
ok. PR from a fork?

**Comment by SleeplessByte** [comment]
> ok. PR from a fork?

Yep, you won't be able to directly create a branch here :)

**Comment by tejasbubane** [comment]
Changes in PR look good. But the README description is confusing (maybe because it is a doubly linked list) - I would generally expect to instead and remove from head only (aka stack). But anyways the problem specification also says the same - so seems good.
