### ISSUE TITLE
Curriculum: promote two-fer to core (round 2) 

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#639]
- [ ] sync `two-fer` with the problem specifications, add the `default` argument instead of calling with `''`.
- [ ] promote `two-fer` to core, right after `hello-world`

**Comment by tejasbubane** [comment]
@SleeplessByte Comment on slack:

![Screenshot 2019-03-27 at 3 02 20 PM](https://user-images.githubusercontent.com/980783/55065271-856d4b80-50a1-11e9-8770-f7850d99e45e.png)

**Comment by SleeplessByte** [comment]
@tejasbubane taken care of at slack :)
