### ISSUE TITLE
Makefile vs JS scripts

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#646]
See sample js files in :

**Makefile**:
* Simple elegant bash commands
* Already in place - tiny changes required.
* Needs separate software on windows (like Cygwin etc)

**JS Script**
* Single language everywhere - assuming contributors already have nodeJS installed
* Not as elegant as Makefile - extremely elaborate for simple task like copying a file: [examples](https://github.com/exercism/javascript/tree/d131c88a91a65f2a07d130942fee381f53daf899/bin/tools)

(Please use 👍 to make the change to JS Script and 👎 to stay with Make)

**Comment by SleeplessByte** [comment]
I would also want to add that:

**Makefile:**
- there is _significant_ overhead for new contributors who don't know make and don't use bash (think: using guis a lot, are on windows, or use a different non-bourne style shell) 
- make commands are easy to get wrong cross-platform, even if a windows user has cygwin / bash installed

**Comment by iHiD** [comment]
Sounds good to me.

**Comment by tejasbubane** [comment]
As of now I prefer Makefile for the [simplicity](https://github.com/exercism/javascript/pull/647/files). But my opinion is biased since I don't use windows and makefiles work flawlessly on Unix systems.

Should we investigate any JS libraries that ease out the process and reduce the elaborate handrolled scripts? I found one https://github.com/jakejs/jake but did have a proper look yet.


>  there is _significant_ overhead for new contributors who don't know make and don't use bash 
> (think: using guis a lot, are on windows, or use a different non-bourne style shell)

Makefiles will not be changed by contributors most of the times. Maybe we should add instructions to install Cygwin for windows contributors? 

> make commands are easy to get wrong cross-platform, even if a windows user has cygwin / bash
> installed

I did not know this. Any specific examples?

**Comment by iHiD** [comment]
What's the Makefile actually do here?

**Comment by SleeplessByte** [comment]
> What's the Makefile actually do here?

Copy a few top-level files, create a temporary directory, copy in all the exercise tests, and rename example.js to the correct filename -- then lints and runs tests.

> As of now I prefer Makefile for the simplicity. But my opinion is biased since I don't use windows and makefiles work flawlessly on Unix systems.

I work with both which is why I know the pain. Make is _really_ not straightforward on windows, even with cygwin.

> I did not know this. Any specific examples?

Yeah, the most simple one is that anytime you need to escape something it's not the same cross shells; similar to why [cross-env](https://github.com/kentcdodds/cross-env) exists.

> Makefiles will not be changed by contributors most of the times. Maybe we should add instructions to install Cygwin for windows contributors?

If we stay with make, I 👍 this proposal -- I think #287 is also very relevant.

> Should we investigate any JS libraries that ease out the process and reduce the elaborate handrolled scripts? I found one https://github.com/jakejs/jake but did have a proper look yet.

If we move to JS scripts, then 👍 this proposal!

**Comment by tejasbubane** [comment]
>What's the Makefile actually do here?

Ohh right sorry for not clarifying that in the issue.

Makefile does a few things in this repo:

1. Copy `package.json` from the root directory to each exercise directory. This makes sure all files being served to users are in sync. Contributors doing any changes to `package.json` are supposed ro run this and commit changes.

2. To be sure contributors making any change to `package.json` in project root have propagated (and commited) that change to all exercises, we run `md5` checksum on toplevel and exercise `package.json`.

3. Create a `./tmp_exercises` copy source and test files there. Run tests inside `tmp_exercises` directory. This allows [Jest](https://jestjs.io/) to run tests in parallel and is way faster than running inside in exercise directory.

Soon will be having more files like [babel](https://babeljs.io/) and [eslint](https://eslint.org/) configs to keep in sync.

**Comment by tejasbubane** [comment]
@SleeplessByte Just saw another point in your favour - https://github.com/exercism/javascript/pull/676#issuecomment-490914391

**Comment by SleeplessByte** [comment]
Ah yes. I also believe we should update `CONTRIBUTING`.

**Comment by SleeplessByte** [comment]
Resolved via #680
