### ISSUE TITLE
npm installation error with first project

### ISSUE THREAD

**Issue by macjabeth** [exercism/javascript#657]
I get this error when attempting to run `npm install` for the first "Hello World" project.

[2019-03-29T21_14_03_786Z-debug.log](https://github.com/exercism/javascript/files/3024584/2019-03-29T21_14_03_786Z-debug.log)
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for electron-to-chromium@^1.3.122
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget 
> npm ERR! notarget It was specified as a dependency of 'browserslist'
> npm ERR! notarget

**Comment by SleeplessByte** [comment]
Are you actually in the `hello-world` directory when you run this command?

We don't do anything with `electron`, so this error does not make sense in regards with exercism.

**Comment by macjabeth** [comment]
![image](https://user-images.githubusercontent.com/8473052/55285331-9d6df500-5357-11e9-8978-7069d1692980.png)
Per the error log, it does state the cwd is in the `hello-world` folder. 🙂 But luckily I just tried running npm install again and everything seemed to work this time without error. I suspect it may have been a bug with one of the sub-dependencies (browserslist?) that was resolved overnight.

**Comment by SleeplessByte** [comment]
Ah. Yes, browserlist is probably used in eslint and babel -- glad that it's fixed!
