### ISSUE TITLE
Awaiting mentor feedback on solution, but all other exercises still locked

### ISSUE THREAD

**Issue by AnnaCate** [exercism/javascript#663]
I submitted my solution to the Two Fer exercise and am awaiting mentor feedback (status says "In Progress"). I would like to move on to the next exercise, but it is still locked (it is my understanding that the submission of my solution should have unlocked the next exercise).

**Comment by SleeplessByte** [comment]
The next exercise will be unlocked once this one is approved.

Can you link your solution page here?

**Comment by AnnaCate** [comment]
@SleeplessByte thank you. My solution page is [here](https://exercism.io/my/solutions/fc842aab24c74617b83615380d9e7428). I guess I am confused since the "Next Steps" box on the right side of the screen says that while I wait for mentor feedback:

> why not try a different exercise on the JavaScript track

**Comment by SleeplessByte** [comment]
> why not try a different exercise on the JavaScript track

Ah yes, if you scroll down on the [track page](https://exercism.io/my/tracks/javascript) you can see the side exercises. These become available after _each core exercise_.

That said, the current queue for `two-fer` is about 4 days!

**Comment by AnnaCate** [comment]
Oh I see. Thank you for clarifying!

**Comment by SleeplessByte** [comment]
No problem! 😄
