### ISSUE TITLE
Unable to download Resistor Color Duo Core Exercise

### ISSUE THREAD

**Issue by nmegrant** [exercism/javascript#664]
Whenever I try to download the exercise Resistor Color Duo I receive the following error message: Error: unable to parse API response - invalid character '<' looking for beginning of value.
![Screen Shot 2019-04-10 at 2 14 56 PM](https://user-images.githubusercontent.com/37487734/55846993-ce41fb80-5b9b-11e9-8c76-8e50f9fc9148.png)

I also noticed the exercise doesn't look the same as the other ones when viewed from the JavaScript main page - there is no description of the exercise visible. 
![Screen Shot 2019-04-10 at 2 18 52 PM](https://user-images.githubusercontent.com/37487734/55847026-efa2e780-5b9b-11e9-84b9-b031817387fe.png)

**Comment by tejasbubane** [comment]
Thanks for reporting @nmegrant. This exercise was previously called `resistor-colors` and was recently renamed to `resistor-color-duo` which seems to have caused the issue. Although I am unable to figure out exactly why, I have asked others for help and will get back to you soon.

**Comment by tejasbubane** [comment]
@nmegrant I just tried and was able to download the exercise. Can you try again?

If you still see the error, can you run the same download command using `--verbose` option and paste the output here? Please be sure to remove your auth-key from `Authorization: Bearer <....key....>` before pasting the result here.

**Comment by nmegrant** [comment]
Still no luck. Here is the output when I tried it with ```--verbose```


========================= BEGIN DumpRequest =========================
GET /v1/solutions/latest?exercise_id=resistor-color-duo&track_id=javascript HTTP/1.1
Host: api.exercism.io
Authorization:
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 500 Internal Server Error
Content-Length: 1443
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Wed, 10 Apr 2019 10:01:53 GMT
Server: nginx/1.10.3 (Ubuntu)
X-Request-Id: a0196e17-8569-4168-a5f7-8b7500fde036
X-Runtime: 0.159397

<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <link rel="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900|Montserrat+Alternates:400,700|Dosis:800"/>
  <style>
    * { box-sizing: border-box }

    html {
        @include normal-font;
        font-size: 62.5%;
        letter-spacing: 0;
    }

    body {
        z-index:0;
        margin: 0;
        @include normal-font;
        @include font-size(14);
        color:#333;
        padding: 0 0 env(safe-area-inset-bottom) 0;
    }
    .heading-bar {
      background:#22333b;
      height:40px;
      margin-bottom:150px;
      padding: env(safe-area-inset-top) 0 0 0;
    }
    img {
      display:block;
      margin: 0 auto 50px auto;
      width: 120px;
      height: 92px;
    }
    p {
      font-family: "Lato", 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size:18px;
      line-height:18px;
      font-weight:300;
      color:#333;
      margin:0 0 6px 0;
      text-align:center;
    }
    a {
      color:#333;
      text-decoration:underline;
    }
  </style>
</head>

<body>
  <div class="heading-bar"></div>
  <img src="https://assets.exercism.io/sad-icon.png"/>
  <p>Oh dear, something's not working here. Sorry about that.</p>
  <p>Continue by heading back to <a href="/">the homepage</a>.</p>
</body>
</html>

========================= END DumpResponse =========================

Error: unable to parse API response - EOF

**Comment by SleeplessByte** [comment]
@iHiD

**Comment by tejasbubane** [comment]
@nmegrant Should be fixed now. Please feel free to reopen this issue if you still face problems.

**Comment by nmegrant** [comment]
@tejasbubane Success! Thanks for the help!

**Comment by nmegrant** [comment]
Hi @tejasbubane - I think I spoke too soon. When I go into the resistor-color-duo directory it is empty. I tried deleting it and re-downloading, but still empty. 

![Screen Shot 2019-04-15 at 9 57 52 AM](https://user-images.githubusercontent.com/37487734/56099789-89d0aa00-5f65-11e9-8021-42d8e5b45931.png)
![Screen Shot 2019-04-15 at 10 00 27 AM](https://user-images.githubusercontent.com/37487734/56099790-8d643100-5f65-11e9-805e-411717f7e841.png)

**Comment by tejasbubane** [comment]
cc @iHiD ^

**Comment by nmegrant** [comment]
Tried deleting it a third time (using ```rm -r resistor-color-duo```). Double checked it was gone, then re-downloaded but the folder is still empty :(

**Comment by iHiD** [comment]
@nmegrant Can I get another copy of the response please? Specifically this bit:

```
X-Request-Id: a0196e17-8569-4168-a5f7-8b7500fde036
```

**Comment by nmegrant** [comment]
Sure, here is what I got from adding ```--verbose``` to the end of the download command:


========================= BEGIN DumpRequest =========================
GET /v1/solutions/latest?exercise_id=resistor-color-duo&track_id=javascript HTTP/1.1
Host: api.exercism.io
Authorization: 
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:22:55 GMT
Etag: W/"ada4c79ff88d10336db68882b560aad5"
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=3DXE6pCoH3GcMwliIzCt1piEiQ5VeKHT7NYekNEvyY3ovqW5kxZt6ZJUeiljDUtFWpGme2ryQFBjBbV93pIvFHOO03qeSlOKTCDUtK2FhJj%2BGeptgIRlO7S%2BDZqmoDy8YmtxtbaBS%2FjwTMH2iybbxC4Xh7jtD2pibAtoRQ59N2rHUpHGsTNBoyxdbHh8JjP0hUYIH%2BesZdAlhwsy07E1DOVNuD5pVNj9CvlNo1%2FzzJQxYL9n0I%2B2dZGVCsWHRN0bfXXImM%2B%2FTw9f9fO3wsYuwztT--hgJQbmeOtzJDuB%2F9--EIPcdChihZzzo6YijqVwRw%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: bc786478-8023-4c83-a348-c217fb8bf33b
X-Runtime: 0.124511
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


========================= BEGIN DumpRequest =========================
GET /v1/solutions/7609d583483f4e67a0cec0f7e07cc772/files/.eslintrc HTTP/1.1
Host: api.exercism.io
Authorization:
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:22:56 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=VSu72iov6agLDDe44Szh31MLpA5vmpf%2BKbhPaB5wdnkZTXGuh8OBeUjlh7h5ohVEex1O89nJFBGcVd4jcmPQ4PavLecIELnMuhOJ%2FL2JVQp5UCJVd2gN89cSCiwXC6ddjJ8bAAvPeGGFD38b2k4vK6jLiOZW%2F9L1Z7BwzoLDJajBn6zsmoiIdPMDl4L6vbTajqM6Q%2FVHgMou0yGSL7MTy2Xd4nzV2tSoOioMxBp%2BI2O7xYcCyUAasUqZCpwsVXIwqzIEPw%3D%3D--GhCHBAUcndrnNJgd--NgGxee9zXxV%2Bqm0nLFZVow%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: abca1e5f-bdad-494b-b821-f290bd9a2632
X-Runtime: 0.090177
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


========================= BEGIN DumpRequest =========================
GET /v1/solutions/7609d583483f4e67a0cec0f7e07cc772/files/README.md HTTP/1.1
Host: api.exercism.io
Authorization:
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:22:58 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=vzrbaMFkX%2FGuQQ2hsgeA4g%2FWFPyWz9vd2os6KXkz%2FVxfa3%2FiDgNxygTsGxBKiEbO9O431jrkeGCUvGsqNCAuLz8Ai3nTcupW7WbiDHmxJvliG0c2cuzzkFbXCIy9qaIwWsD%2BgYP63mVcQsynaWkDZgbjlacR3rBan9DAQe4CZ3otleh1BsVw%2BdeI3YwBaP1R0ok%2BMyK0mlHZFv9gFtr%2Fmgrl2ETa%2BLm%2Bhw7ZqBozVFBlXJJFt9YISc%2FCOgavLP4FJBNDNQ%3D%3D--dxNS%2BDd%2Fz9f3YTAq--iYol%2FEnpYmROjdBppGd1XQ%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: f7b7f291-0289-4f6d-a6d1-6991d2993ed1
X-Runtime: 0.092221
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


========================= BEGIN DumpRequest =========================
GET /v1/solutions/7609d583483f4e67a0cec0f7e07cc772/files/babel.config.js HTTP/1.1
Host: api.exercism.io
Authorization: 
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:22:59 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=FzUfD2o6hSUbNt7PKiQj10oNAJORMETI4mP9BJftZBPDHAXM34ORcRBqcCPiIRx2Usn42MGO9jTSsU%2FgBhbYHhcviQZkVR57kpc7V7XUPJE4u5%2B4JjLuvAISrWEI02UKjJS7jAsRvbF8eH0ueikJ4TJ2inIel4pfzljp%2BU0%2BZRzjCZNQZrj7Nk%2Fqhxf3h0zIA8FRC5soEivK7Fyjkyh4ghKNdv3voGmiM0dlxlRiltJHMBH3IgZjLLhsq3WkPv3LkMRP2TM1jF4Okw%3D%3D--CBtlGExEfUajv0RH--4bqCesUYwM%2FEq3sWD08nUw%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 44adfff2-6c57-4f60-9c45-e9daedf22de1
X-Runtime: 0.093293
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


========================= BEGIN DumpRequest =========================
GET /v1/solutions/7609d583483f4e67a0cec0f7e07cc772/files/package.json HTTP/1.1
Host: api.exercism.io
Authorization:
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:23:01 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=dcgIoxQCKhPrjaB3HpXb3YN8SqLPASohBWaEiGiaZnuCu%2FQhJTZREf23foOPbEHWvM5viZbrsz61UJgxfkpRXeQPKBhTzYfrhxcL5UPNF4oRf%2FllB9hM2%2FfvKzx5LXUK9VCsZq5SCdcCy2aYrZCq7Azmzp22AA9pc5yOQGsJPJGML4eOnwFj5X9JazGA20Hm%2FqG7Sh%2FZff7xUSimW%2FRC0JHzyXKLtZHC1Ti2YSn9n7mKhgOhQDqOQnr9sNeie0zSamBEJuBaVw%3D%3D--Ho3oAXxR4sPbpJxu--oaQuft5OU%2FA10BZcNCOO0g%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 9ac989ff-9bab-4885-877b-d176d586bdf4
X-Runtime: 0.090115
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


========================= BEGIN DumpRequest =========================
GET /v1/solutions/7609d583483f4e67a0cec0f7e07cc772/files/resistor-colors.spec.js HTTP/1.1
Host: api.exercism.io
Authorization: 
Content-Type: application/json
User-Agent: github.com/exercism/cli v3.0.11 (darwin/amd64)


========================= END DumpRequest =========================


========================= BEGIN DumpResponse =========================
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 16 Apr 2019 11:23:02 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.10.3 (Ubuntu)
Set-Cookie: site_context=normal; domain=.exercism.io; path=/
Set-Cookie: _exercism_session=EyzYOx48ig4C9ucs6rY5u21H8SKcThqEE%2Frq12C2ou88Esb1jgBIgEIwO8VUM1CULeN%2FwshOiFr7TqlCM9ohHJW%2BXP%2FtGLCUM%2Br%2BWivPdO4q1S5cvMpwibPCny%2BxVA5uXZOgC2I1RSoRqOJJ8si7EQmzZmdDhw5PmFK0IhpAeR8fFQs91IGRzcY%2B11R2C0sjXxjpJ2eRdxUScnUjUKOewB6AdUEdiu87X67I8cVOuhcKZuA75T%2F5iWm%2BcVL6S9S8lPqefJYd3ZDLpSRrmfti2lIP--Q6nm21oSW1Cxk%2Fyg--gKpCShtWhkTMAYwH5yzJOQ%3D%3D; domain=.exercism.io; path=/; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: ad70d865-9d04-4d04-b29c-7e6f6d98890b
X-Runtime: 0.093806
X-Xss-Protection: 1; mode=block


========================= END DumpResponse =========================


Downloaded to
/Users/ngrant/Exercism/javascript/resistor-color-duo

**Comment by iHiD** [comment]
Sorry. There was a second bug here (basically a duplicate of the first). Could you try again now pls?

**Comment by nmegrant** [comment]
It works!  Downloaded successfully, checked the directory andeverything was there, ran npm install, etc and all looks to be working. Thanks for the fix!

**Comment by iHiD** [comment]
Great. Thanks for confirming :)
