### ISSUE TITLE
Wordy: Intended verification for `ArgumentError`

### ISSUE THREAD

**Issue by serixscorpio** [exercism/javascript#674]
In the wordy [test suite](https://github.com/exercism/javascript/blob/4762107967273cfec8d7bcc69121dedb1c2b48c1/exercises/wordy/wordy.spec.js#L74-L86), the argument of `toThrow` method is `new ArgumentError()`, but based on [jest documentation](https://jest-bot.github.io/jest/docs/expect.html#tothrowerror), it seems the intended verification was perhaps just `ArgumentError` (in other words, to verify the error is of a certain class).
So maybe change from `toThrow(new ArgumentError())` to `toThrow(ArgumentError)` ?

**Comment by tejasbubane** [comment]
Right. Would you be willing to send a PR to make the change?
