### ISSUE TITLE
Exports can be confusing for beginner-level exercises

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#678]
From a comment on [this `two-fer` solution](https://exercism.io/mentor/solutions/45e039027cf64520b1416c3c559aad6c):

> I had to add export to my code in order to get it to work. I understand how modules and webpack work, but doesn't it seem weird to include advanced knowledge like this in beginner exercises?

We changed all exercises from default to named exports, but in either case it can be confusing for beginners who are not aware of how modules & exports work.

One solution I see is adding stub files for all core exercises. Thoughts?

**Edit:** Another instance today: 

Mentee had not exported the function and just had:

```
let twoFer = () ...
```

My comment on [`two-fer` exercise](https://exercism.io/mentor/solutions/10a3f833b23c444dbabf61ab4a1a7b71):
> You will have to export your function so that tests can use it.

Reply from mentee:
> Hi, thanks for the review. What do you mean by exporting my function?

This was my bad in assuming (s)he would be aware of `exports` but is still relevant to this issue.

**Comment by SleeplessByte** [comment]
> One solution I see is adding stub files for all core exercises. Thoughts?

Yes. This is the solution and I don't think we should do anything else. Other tracks have gone the same route.

**Comment by tejasbubane** [comment]
There are 18 core exercises. Should we add stubs for all or first few ones and then let it loose by adding a note in the README? We can take a call based on difficulty level.

**Comment by SleeplessByte** [comment]
There are 2 approaches I've seen:

- Either _all_ **core** exercises
- Exercises with a difficulty lower than 6, the ones of 6 and higher _do_ have a note that there is no stub.

**Comment by tejasbubane** [comment]
> Exercises with a difficulty lower than 6, the ones of 6 and higher _do_ have a note that there is no stub.

This option looks good for now. Creating a separate issue for this. Thanks!

**Comment by tejasbubane** [comment]
Closing in favor of #679
