### ISSUE TITLE
Add stub files

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#679]
Taken from #678 

Exports required in exercise files can be quite confusing for beginners. We would like to make it easier by adding stub files for `core` exercises with difficulty level `less than or equal to 6`. 

See [config file](https://github.com/exercism/javascript/blob/master/config.json) for core and difficulty levels. `hello-world` exercise has an [example stub file](https://github.com/exercism/javascript/blob/master/exercises/hello-world/hello-world.js).

Note: The filename should be exactly `<exercise-name>.js`. eg. For `two-fer` exercise, there should be a file `exercises/two-fer/two-fer.js` with the following contents:

```js
//
// This is only a SKELETON file for the 'Two Fer' exercise. It's been provided as a
// convenience to get you started writing code faster.
//

export const twoFer = () => {
  //
  // YOUR CODE GOES HERE
  //
};
``` 

`twoFer` here is the function name as required by the [test cases](https://github.com/exercism/javascript/blob/master/exercises/two-fer/two-fer.spec.js).

Feel free to comment below if you need any help.

**Comment by ankorGH** [comment]
@tejasbubane Is someone working on this? If not I will like to work on it.

**Comment by tejasbubane** [comment]
@ankorGH Nobody else is working on this. Go ahead.

**Comment by SleeplessByte** [comment]
Closed via https://github.com/exercism/javascript/commit/189a99767ebe2271eff2b4a784539cec9334dea5
