### ISSUE TITLE
Use airbnb-eslint config

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#681]
From https://github.com/exercism/javascript/pull/645

Turn on [airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) for maintaining via a script that switches this.

In a later change, we should turn on several rules that guard against potential bugs, such as `no-shadow`, `no-undefined`, `no-var`; additionally we can add stylistic consistency without forcing style choises such as consistent spacing (but not required).

We should stay with `eslint:recommended` for exercises (end users) and use airbnb only for this repo. @SleeplessByte 

Wait for https://github.com/exercism/javascript/pull/680 to be merged so that we can exclude `airbnb` from `package.json` checksum CI task.

**Comment by SleeplessByte** [comment]
Yes yes yes! This is exactly what I meant.
