### ISSUE TITLE
Clock Exercise: Test suite, example, and stub file do not align

### ISSUE THREAD

**Issue by Tyresius92** [exercism/javascript#695]
It seems as though the expected solution is different from the provided stub file. The stub file contains a class `at` with stubbed out functions, but the tests won't run on it, resulting in `TypeError: Class constructor at cannot be invoked without 'new'`. 

Meanwhile, the example solution uses a function that returns an object with functions as properties, I think? (I'm not super familiar with the construct being used, so don't know if it has a formal name. If someone wanted to point me at a relevant resource, that would be appreciated!)

I don't know which solution to suggest, but at a minimum I don't think we should be providing a stub file that points students in a direction that's incompatible with the expected solution.

**Comment by SleeplessByte** [comment]
I agree. I actually prefer to model this as a proper `class` named `Clock`.

Would you be willing to PR a change to `example.js`, `clock.js` and `clock.spec.js`?

**Comment by Tyresius92** [comment]
Yeah, I'll work on that either today or tomorrow. You can consider it in progress. :)
