### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/javascript#705]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by SleeplessByte** [comment]
Closing as we already provide this.

**Comment by tejasbubane** [comment]
Opening because of https://github.com/exercism/javascript/issues/721 & https://github.com/exercism/javascript/pull/722

**Comment by rsuttles58** [comment]
I'm going to start knocking out some of these stubs for hacktoberfest.  I may do one in the first pull and if those get approved cleanly then I may bang out a few more.

**Comment by MaruthiMohanReddyPutha** [comment]
Hi team, I would like to contribute to adding stub files to the repo. Could you please provide me the access to create a branch and pull requests?

**Comment by tejasbubane** [comment]
Please check linked PRs to avoid duplication of work.

**Comment by Roshanjossey** [comment]
@tejasbubane, does it make sense to keep a checklist for contributors to better understand which ones are done and which ones are not?

**Comment by tejasbubane** [comment]
Only `diffie-hellman` left.

**Comment by SleeplessByte** [comment]
https://tracks.exercism.io/javascript/master/stubs yasss.

**Comment by tejasbubane** [comment]
Completed and verified by https://github.com/exercism/javascript/pull/722
