### ISSUE TITLE
Add new topics to exercises related to data structures

### ISSUE THREAD

**Issue by alirezaghey** [exercism/javascript#712]
Issue #667 proposed normalizing the topics across exercises which was addressed in PR #711.

**data_structures** as a topic was removed from seven exercises, since it doesn't have a corresponding topic.

At least some of these seven exercises, and may be even other exercises, seem good candidates for a tag like **data_structures** or similar, since they cover this topic.

The seven exercises are as follows:

- matrix
- linked list
- list ops
- spiral matrix
- custom set
- circular buffer
- simple linked list

In my humble opinion, data structures, like algorithms, is a topic of interest to many students, and having them combined under one meaningful topic is helpful.

Before adding a new topic to this exercises addressing the subject of data structures, an issue must be opened at [problem-specifications](https://github.com/exercism/problem-specifications) to add the missing topic.

**Comment by SleeplessByte** [comment]
@ErikSchierboom @F3PiX @kytrinyx @iHiD I think these all match one of our "exercise categories". This would probably be a possible moment to add this as a topic?

**Comment by ErikSchierboom** [comment]
Sounds like a good plan. I've checked the existing topics list and it indeed doesn't include this topic

**Comment by kytrinyx** [comment]
I'll add it to the problem specifications document now.

**Comment by alirezaghey** [comment]
I like to go through all the JS exercises and add the topic to those where it seems reasonable. Is that OK?

**Comment by SleeplessByte** [comment]
@alirezaghey yes please. I think the seven you listed are prime candidates.
