### ISSUE TITLE
eslint-utils >=1.2.0 <1.4.1 have a critical vulnerability; needs to be updated to >= 1.4.1 

### ISSUE THREAD

**Issue by alirezaghey** [exercism/javascript#717]
It appears that at least one of our eslint packages is using an older version of eslint-utils, which is vulnerable.

I'm not sure if this will be solved automatically, or even if I should have raised the issue here.

Here's the issue on[ eslint-utils' repository](https://github.com/mysticatea/eslint-utils/security/advisories/GHSA-3gx7-xhv7-5mx3).

Let me know if I can be of any help.

**Comment by SleeplessByte** [comment]
This has been fixed in #716.

We don't push `package-lock` #703 at the moment (and don't plan to soon). Students can fix this warning by running an `audit --fix` locally, but since this is not actually dangerous for the student, they can also just leave it.
