### ISSUE TITLE
Meetup doesn't have a skeleton file

### ISSUE THREAD

**Issue by hayashi-ay** [exercism/javascript#721]
Hello. I'm student of the exercism javascript course.
When I download Meetup, I found that a skeleton file is not downloaded.
I mean `meetup.js` is not downloaded.

I think it related to #679 and `meetup.js` should also be added in that time.

**Comment by SleeplessByte** [comment]
Yep, there is [no stub present](https://github.com/exercism/javascript/commits/master/exercises/meetup).

**Comment by tejasbubane** [comment]
Part of https://github.com/exercism/javascript/issues/705

**Comment by rsuttles58** [comment]
I submitted a PR for this specific issue and will be doing other stubs if this checks out.

**Comment by aimorris** [comment]
This issue can be closed. There is now a skeleton file for Meetup.

**Comment by tejasbubane** [comment]
Closed by https://github.com/exercism/javascript/pull/748
