### ISSUE TITLE
Update README.md (scripts vs make)

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#731]
The README.md is outdate. We no longer use make. It should be updated to explain how to use the scripts.

**Comment by ThinkHattke** [comment]
@SleeplessByte can I work on it?

**Comment by SleeplessByte** [comment]
Certainly. You can use the pr for contributing guidelines as guidance.

**Comment by SleeplessByte** [comment]
@ThinkHattke it's been over a week. Since this is actively blocking new contributors, I've implemented it in #744
