### ISSUE TITLE
Add new exercise: book-store

### ISSUE THREAD

**Issue by mcampourcy** [exercism/javascript#733]
[problem specification][problem-specification] | [description][readme] |  [canonical data][canonical-data]

[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/book-store
[readme]: https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/description.md
[canonical-data]: https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json

**Comment by SleeplessByte** [comment]
@mcampourcy I've added some helpful links to this issue. Let me know if you need anything!

**Comment by mcampourcy** [comment]
Great, thanks ! :+1:

**Comment by mcampourcy** [comment]
@SleeplessByte I can't download the Linux version of [configlet](https://github.com/exercism/configlet/releases/tag/v3.9.2), is it normal ?

**Comment by SleeplessByte** [comment]
Ref #747 

How is it going? Need any help?
