### ISSUE TITLE
Updating circular-buffer

### ISSUE THREAD

**Issue by TomPradat** [exercism/javascript#736]
https://github.com/exercism/javascript/blob/ba572f1b0708d8a7d3fc1cb94a4dded9f4b7a8fb/exercises/circular-buffer/example.js#L43-L52

I think it would make more sense for the `CircularBuffer` to be an object

**Comment by SleeplessByte** [comment]
Sure. You can try it. The `example.js` however is not meant to be an _optimal_ solution. Just proof that there exists at least á solution!

**Comment by TomPradat** [comment]
Alright, can the pupils see this solution though ? I'll work on a PR and try to improve the example :)

**Comment by SleeplessByte** [comment]
They can if they go on GitHub. Not via the platform :)

**Comment by TomPradat** [comment]
Seems to have been done, i'm closing this issue then
