### ISSUE TITLE
Add new exercise: grep

### ISSUE THREAD

**Issue by TomPradat** [exercism/javascript#737]
[problem specification][problem-specification] | [description][readme] |  [canonical data][canonical-data]

[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/grep
[readme]: https://github.com/exercism/problem-specifications/blob/master/exercises/grep/description.md
[canonical-data]: https://github.com/exercism/problem-specifications/blob/master/exercises/grep/canonical-data.json

**Comment by SleeplessByte** [comment]
@TomPradat go ahead. I've added some helpful links for you!

**Comment by SleeplessByte** [comment]
How is it going? Need any help?

**Comment by TomPradat** [comment]
Sry i wasn't available this week-end. I barely started, i'll keep you in touch :)
