### ISSUE TITLE
 Add new exercise: scale-generator

### ISSUE THREAD

**Issue by seeksort** [exercism/javascript#751]
[problem specification][problem-specification] | [description][readme] |  [canonical data][canonical-data]

[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/scale-generator
[readme]: https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/description.md
[canonical-data]: https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/canonical-data.json

**Comment by SleeplessByte** [comment]
I've added some useful links for you!
