### ISSUE TITLE
Sync Saddle Points with v1.5.0

### ISSUE THREAD

**Issue by ovidiu141** [exercism/javascript#764]
Test issues:

- Unlike the other tests, there is an additional space in the input matrix of the _'extracts a column'_ test (after the last '\n'). This makes the splitting to not work properly, so the test fails even if the code is correct.
`       const matrix = new Matrix('1 2 3\n4 5 6\n7 8 9\n 8 7 6'); 
`
- Tests are build following a 0-based indexing

- Tests are not using the canonical data.

- I also think a better approach would be to use nested arrays as input to the Matrix constructor e.g. `[[9, 8, 7], [5, 3, 2], [6, 6, 7]]` instead of strings, just like in the Typescript version of the same problem.

**Comment by SleeplessByte** [comment]
Yes. This exercise is not up to date :) Welcoming PRs!

**Comment by ericp3reira** [comment]
May I take this?
