### ISSUE TITLE
Add new exercise: bank account

### ISSUE THREAD

**Issue by brendanmckeown** [exercism/javascript#767]
[problem specification][problem-specification] | [description][readme] |  [canonical data][canonical-data]

[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/bank-account
[readme]: https://github.com/exercism/problem-specifications/blob/master/exercises/bank-account/description.md
[canonical-data]: https://github.com/exercism/problem-specifications/blob/master/exercises/bank-account/canonical-data.json

**Comment by SleeplessByte** [comment]
I've update the issue with some additional links @brendanmckeown !

**Comment by brendanmckeown** [comment]
@SleeplessByte - with porting this exercise to the JS track, was the intention to include the concurrency/multi-threaded tests?

**Comment by SleeplessByte** [comment]
Good question. Since JavaScript only sorta-kinda-but-no-really has multi-threading here, in this track I don't think it makes sense to have those. I think your PR makes sense :)

**Comment by SleeplessByte** [comment]
Fixed by #888
