### ISSUE TITLE
Bottleneck in  { JavaScript: Linked List } core exercise queue - wasn't visited for 15 days

### ISSUE THREAD

**Issue by clockelliptic** [exercism/javascript#780]
I imagine that this problem probably is difficult if you've never encountered it before, and it can generate 50-60 lines of code if implemented without using JavaScript's array object. I imagine that could be why I've been in queue for so long.

That said, I haven't moved ahead in the queue in about 5 days. (also I've moved backward in the queue several times... and in addition to this the median completion time was 2 days for about a week straight). 

I don't mind sitting tight and doing side exercises, just wondering because things were moving along at a much quicker pace until this particular problem. I seem to be stuck in line! Thank you.

**Comment by SleeplessByte** [comment]
It's on the list to be replaced in the core :)

**Comment by nicolabuckhurst** [comment]
I also seem to be stuck in the queue for the Linked List exercise. It has been saying there are 3 solutions ahead of me since I submitted and I don't seem to move.

**Comment by SleeplessByte** [comment]
@nicolabuckhurst you can always ping me with an URL and I will review it for you
