### ISSUE TITLE
Add new exercise: Yacht

### ISSUE THREAD

**Issue by ovidiu141** [exercism/javascript#798]
[problem specification](https://github.com/exercism/problem-specifications/tree/master/exercises/yacht) | [description ](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/description.md)| [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/canonical-data.json)

**Comment by SleeplessByte** [comment]
Sweet. Thanks @ovidiu141 ! Are you on the slack by any chance?

**Comment by ovidiu141** [comment]
@SleeplessByte No, I'm not.
