### ISSUE TITLE
Sync script deletes exercise versions

### ISSUE THREAD

**Issue by tejasbubane** [exercism/javascript#825]
Our CI scripts compare [`package.json` file in root](https://github.com/exercism/javascript/blob/master/package.json) with the one in each exercise. But `version` in package.json is for book-keeping to keep track of [canonical versions](https://github.com/exercism/problem-specifications/blob/63bb34cde0d4e262e3f34b5dc2c1f4c6014e527e/exercises/hello-world/canonical-data.json#L3) & hence is different for each exercise. The CI script deletes field from JSON before comparing.

When we change/update any package, we sync the root file with all exercises using [sync script](https://github.com/exercism/javascript/blob/master/scripts/sync). This uses the same helper function above which deletes the field which results in deletion of all versions after sync. Issue was first noticed in https://github.com/exercism/javascript/pull/723 and effect can be seen here: https://github.com/exercism/javascript/pull/824/files#diff-29adfdb706266f78376d86b88aed872aL3

**Comment by paparomeo** [comment]
I think I have an "almost solution" for this one. Just need to figure out one final detail, so assigning it to myself.
