### ISSUE TITLE
Exercise instruction suggestions to help beginners

### ISSUE THREAD

**Issue by TCE-1** [exercism/javascript#842]
Hi,

I've just started on this site to help with learning JavaScript.  Concept seems awesome and on my 2nd exercise I am already getting valuable feedback that has me learning new things.  

I found the instructions a bit confusing for setting things up.  This suggestion will only be valuable if the intention of the exercise is to be noob friendly.  

When you visit the first exercise you are given instructions on the exercise itself.  As you read through you get to "setup".  Now you may confuse whether this is set up for this specific exercise or main setup to use this platform.  Its also confusing that these "setup" instructions seem to come up in other exercises as well.

Also, the "setup" links to instructions to install node.  it is then followed by `npm install` and `npm test`.  This may just be a noob mistake but I spent a ton of time here not knowing how to get things working.  I felt silly when I found the answer because all I had to do was look to the right side of my screen and there were the instructions for installing the Exercism "cli" in a box labelled "Getting started".  I think having the first focus when landing on the page be the "setup" and having all the necessary steps listed together would help the confusion here.

After that I figured out that I had to download the exercise but not after first writing my own script and trying to use `npm test` a few times.  After that it took a bit more time and googling to figure out how to run the tests.

It could just be me who got lost at the start here but because it was frustrating I thought I would outline the challenges.  Especially because this seems like a super valuable tool for beginners/intermediates and some may just give up after spending an hour trying to get through a "Hello World" exercise.  And no one wants to post and ask for help on a "Hello World" exercise, lol.

**Comment by SleeplessByte** [comment]
I absolutely agree that we should move the DOWNLOAD THE CLI step to this instruction manual :)

**Comment by tejasbubane** [comment]
@TCE-1 [Installation docs](https://github.com/exercism/javascript/blob/818a86679ce334c9f118c3f9ae0966b839f0e11d/docs/INSTALLATION.md) have been improved. They will reflect on the website shortly. Let us know if you feel anything else should be improved.
