### ISSUE TITLE
Add notification about npm output

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#848]
`npm` outputs very scary looking "vulnerability" messaging, multiple times, all the way down the dependency tree, when there is a CVE for such dependency. About 100% of the time, these warnings are **not** applicable to the use-case of this track and can safely be ignored. 

Add a message about this in the instructions to avert issues like https://github.com/exercism/exercism/issues/5212.

**Comment by iHiD** [comment]
Is there any silent mode or piping stderr or anything that we could incorporate into the command?

**Comment by SleeplessByte** [comment]
Yeah -- but that would hide stuff to help them resolve their configuration / local system.

**Comment by tejasbubane** [comment]
We can ask npm `not` to run `audit` after `npm install`. Using `npm-config`: https://docs.npmjs.com/misc/config#audit

**Comment by chiptus** [comment]
Maybe fix the vulnerabilities?

**Comment by tejasbubane** [comment]
@chiptus 
> Maybe fix the vulnerabilities?
1. They come up pretty often
2. Students cannot always get the newer files: https://github.com/exercism/exercism/issues/5212#issuecomment-599550207

**Comment by SleeplessByte** [comment]
And they're usually _not_ vulnerabilities in the sense that there is an attack surface/vector.
