### ISSUE TITLE
Help out with V3

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#850]
**Are you new and want to help out? :wave: in the channel on slack, or here. We will help you get [set-up](https://exercism-team.slack.com/archives/CC3JABXMF/p1587488025014500?thread_ts=1587487633.013600&cid=CC3JABXMF).**

## Important resources

1. [The Features of V3](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)
1. [The Rationale for V3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md)
1. [About Concept Exercises](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md) (and [how to make one 📽](https://www.youtube.com/watch?v=gkbBqd7hPrA))
1. [How to implement a new concept exercise](https://github.com/exercism/v3/blob/master/languages/javascript/reference/implementing-a-concept-exercise.md)

## Handy links

| | |
|-|-|
| ~:bar_chart:~ | [~Project Board~](https://github.com/exercism/v3/projects/14?fullscreen=true) |
| :books: | [Open Issues](https://github.com/exercism/javascript/issues?q=is%3Aissue+is%3Aopen) |
| :gift: | [Open Pull Requests](https://github.com/exercism/javascript/pulls?q=is%3Apr+is%3Aopen)
| ~:house_with_garden:~ | [~v3 Docs Website~](https://exercism.github.io/v3/#/) (browsable reference of all v3 information) |
| ~:gear:~ | [~JavaScript Concept Reference~](https://exercism.github.io/v3/#/languages/javascript/reference/README) (repository of information about concepts) |
| :wrench: | [JavaScript Track Maintenance](https://tracks.exercism.io/javascript) (live check list)  |
| :alembic: | [JavaScript Preview Playground](https://exercism-playground.derk-jan.com/) (play v3 exercises)  |

## Channels to check out

- [#maintaining-javascript](https://exercism-team.slack.com/archives/CC3JABXMF)  (for v3 javascript)
- [#v3](https://exercism-team.slack.com/archives/CR91YFNG3) (general v3 channel. we also announce cross-track calls, meetings etc. here)
- [#website-copy](https://exercism-team.slack.com/archives/CFYR19MBR) for anything relating mentor notes
- [#automated-analysis](https://exercism-team.slack.com/archives/CFMEG1H0C) for anything related to representers and analyzers
- [#automated-tests](https://exercism-team.slack.com/archives/CMNQSQZUY)  for anything related to test runners

**Comment by peterchu999** [comment]
Hi there i'm new could you help me to get set up ?

**Comment by SleeplessByte** [comment]
Definitely @peterchu999. 

1. If you go into the `exercism/v3` repo, into our track and edit the `maintainers.md` file, that'd be great -- this is how everyone knows that you're helping out.
2. You also also need to open a PR to edit the `exercism/javascript` `maintainers.json` file with `show on website` set to `false`. This will give you rights on the repositories in question! (So you can edit labels, assignments, reviews etc.)

Then make sure you read doc 1 through 4 and come back here! 🔢. I can recommend pressing "become a mentor" on exercism.io, so that you get access to the slack.

**Comment by Upinder123** [comment]
Hi there i'm new could you help me to get set up ?

**Comment by junedev** [comment]
@SleeplessByte In the description of this issue the link "JavaScript Concept Reference" is broken. Also the first channel listed is called "#maintaining-javascript" not "#maintaining-js". Can't PR on an issue so you might want to fix these yourself. :wink:

**Comment by neenjaw** [comment]
@junedev all of the docs/links that were pointed at the v3 repo may or may not be working / updated as that repo is now archived.  The links here just haven't been updated yet since this only happened two weeks ago (but this post is from last April)

The javascript specfic docs are all in [this repo](https://github.com/exercism/javascript) now (eg. [Javascript: implementing a concept exercise](https://github.com/exercism/javascript/blob/main/reference/implementing-a-concept-exercise.md). and there are a number of general v3 docs at [exercism/docs](https://github.com/exercism/docs)

**Comment by junedev** [comment]
@neenjaw Thanks. I read about the move but forgot about it by the time I clicked that link. 🙈

**Comment by SleeplessByte** [comment]
@Upinder123 sorry! I've never seen your message. Are you still interested?

**Comment by junedev** [comment]
V3 is live now. 🥳 Please see the open issues regarding how to help further. You can also use the new explore tasks UI https://exercism.org/contributing/tasks.
