### ISSUE TITLE
Pascal's Triangle Mentoring notes are not up to date

### ISSUE THREAD

**Issue by ghjk-code** [exercism/javascript#864]
The [mentoring notes](https://github.com/exercism/website-copy/blob/master/tracks/javascript/exercises/pascals-triangle/mentoring.md) for the Pascal's Triangle exercise are always mentioning a class whereas [code](https://github.com/exercism/javascript/blob/master/exercises/pascals-triangle/pascals-triangle.spec.js) has changed to use a single function some months ago due to commit #807.

**Comment by ghjk-code** [comment]
Fewww, sorry for my first steps using git on this site, but I have added a commit to handle the new expected code on mentoring notes.

**Comment by SleeplessByte** [comment]
Fixed via https://github.com/exercism/website-copy/pull/1676
