### ISSUE TITLE
ISBN Verifier test failing

### ISSUE THREAD

**Issue by ziyafenn** [exercism/javascript#872]
Hello, 
in the [ISBN Track](https://github.com/exercism/javascript/blob/543112233795c08650728346fa8ef89dcf176f68/exercises/isbn-verifier/isbn-verifier.spec.js), there is a test called `check digit of X should not be used for 0` which is the only one that fails when i run my test.

And i cannot fix it becase i do not understand what this means and what test wants from me :( 

I hope someone can help explain to me what it means. I'll post my code here too:

```
export const isValid = (isbn) => {
  let trimIsbn = isbn.replace(/-/g, "")

  if (trimIsbn.length !== 10) {
   return false
  }
  
  if (/[A-Z]/g.test(trimIsbn.substring(0, trimIsbn.length - 1))) {
    return false
  }

  if ( /\d/g.test(trimIsbn[9]) || trimIsbn.endsWith("X")) {
    if (trimIsbn.endsWith("X")) {
      trimIsbn = [...trimIsbn.substring(0, 9), 10].join("");
    }
    let n = 0;
    let res = 0;
    for (let i = 10; i > 0; i--) {
      if (trimIsbn.length === 11 && n === 9) {
        res = 10 * i
      }
      res += trimIsbn[n] * i
      n++
    }
    console.log(res, "result", res % 11, "reminder")
    return res % 11 === 0
  }

  return false;
};
```

**Comment by SleeplessByte** [comment]
Oof. That's a very weirdly named test! 

You can read the discussion here:
https://github.com/exercism/problem-specifications/pull/924/files/09a2e97057fe01c8a7a28b4b0e242df4d38075b4#r143091157

Let me know if the original, long explanation, is clearer? If not, I'm happy to walk your through it.
