### ISSUE TITLE
Add new exercise : Affine cipher

### ISSUE THREAD

**Issue by TomPradat** [exercism/javascript#886]
[problem-specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/description.md) | [metadata](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/metadata.yml) | [canonical-data](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/canonical-data.json)

**Comment by TomPradat** [comment]
I'll work on this

**Comment by neenjaw** [comment]
Sounds good, @TomPradat are you familiar with the effort to make version 3 of exercism? There is a good opportunity to write content or exercises there too (which would be a big help)!

See this list of issues: https://github.com/exercism/v3/issues?q=is%3Aissue+is%3Aopen+%22%5BJavascript%5D%22+no%3Aassignee+

**Comment by TomPradat** [comment]
Not really, i'll check it out :).

With v3, will the exercises of this repo be moved to the v3 ? In other words, is it useful to implement exercises here too ?

**Comment by neenjaw** [comment]
They will get ported to v3, but the big change in v3 is to let exercises from v2 just to be about practice rather than about teaching JavaScript. So v3-specific exercises aim more to teach a single concept in JavaScript than attempt to solve an open ended problem.
