### ISSUE TITLE
palindrome-products: optimise implementation

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#898]
Don't work on this issue until #895 is merged, or use that PR as a base branch.

The "largest palindrome from four digit factors" test currently takes > 30s to complete. When fixed, replace `test.skip` with `xtest`.

**Comment by tliebert** [comment]
This test case currently prevents the users code from passing the test suite - it returns this case as failed even though the test is skipped.

**Comment by junedev** [comment]
@tliebert Thanks for reporting. We are aware of the issue. @SleeplessByte is working on fixing this.
