### ISSUE TITLE
word-search: sync

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#903]
See CONTRIBUTING.md. 

The following test is missing:

```toml
# Should fail to locate a word that is not in the puzzle
"695531db-69eb-463f-8bad-8de3bf5ef198" = true
```

**Comment by vishal-codes** [comment]
Hey @SleeplessByte Can I work on this issue? and
<a href="https://github.com/exercism/javascript/blob/main/CONTRIBUTING.md#fetch-configlet">This </a> is the section where I have to add this test correct?

**Comment by SleeplessByte** [comment]
@vishal-codes yes! But you don't need to manually add it there. Instead use `configlet sync`. Docs are [here](https://github.com/exercism/docs/blob/main/building/configlet/sync.md). (Link in CONTRIBUTING.md is still broken)

1. `configlet sync`
2. The test then needs to be _manually_ implemented in [`word-search.spec.js`](https://github.com/exercism/javascript/blob/main/exercises/practice/word-search/word-search.spec.js). 
3. Make sure the tests still pass against [`.meta/proof.ci.js`](https://github.com/exercism/javascript/blob/main/exercises/practice/word-search/.meta/proof.ci.js)

**Comment by vishal-codes** [comment]
This is kind of too overwhelming😵 for me but I m trying my best. As mentioned in the docs I ran the command `npx babel-node scripts/sync`. After this when I try to run `configlet sync` the terminal responds with `configlet: command not found`. I need help.

**Comment by junedev** [comment]
@vishal-codes Can you check configlet was installed properly? See https://github.com/exercism/docs/tree/main/building/configlet#usage
As mentioned there you might have to include "bin/" at the beginning when running the command to access the correct folder that contains the configlet program.

**Comment by vishal-codes** [comment]
@junedev How can I check if the configlet was installed properly?

**Comment by junedev** [comment]
I just meant check whether you see configlet in the bin folder after running that fetch script.

**Comment by vishal-codes** [comment]
@junedev Sorry but I think I don't know enough about the sync and testing thing I tried but I am not getting it. I guess I'll have to unassign this issue

**Comment by junedev** [comment]
No problem, thanks for giving it a try.

**Comment by sachinmk27** [comment]
Hi, can I take this up ?

**Comment by qianzhong516** [comment]
Hi, I just made a PR. Please let me know if there is any issue. Thanks

**Comment by sachinmk27** [comment]
Hi, @qianzhong516  didn't want to override 😬 . Had spent some time working on this, so pushed it anyway. Will pick some other issue.
