### ISSUE TITLE
Add new exercise: satellite

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#924]
[problem specification ](https://github.com/exercism/problem-specifications/tree/master/exercises/satellite)| [description](https://github.com/exercism/problem-specifications/blob/master/exercises/satellite/description.md) | [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/satellite/canonical-data.json)

You may find it helpful to follow [this checklist](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md#new-exercise) from the [CONTRIBUTING.md](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md) resource.

**Comment by lpizzinidev** [comment]
Hi 🤚🏻 Can you assign me the exercise?
