### ISSUE TITLE
Add new exercise: zebra-puzzle

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#927]
[problem specification ](https://github.com/exercism/problem-specifications/tree/master/exercises/zebra-puzzle)| [description](https://github.com/exercism/problem-specifications/blob/master/exercises/zebra-puzzle/description.md) | [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/zebra-puzzle/canonical-data.json)

You may find it helpful to follow [this checklist](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md#new-exercise) from the [CONTRIBUTING.md](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md) resource.

**Comment by lpizzinidev** [comment]
Hi! Can I try to implement this?

**Comment by SleeplessByte** [comment]
Sure!

**Comment by joshgoebel** [comment]
@SleeplessByte Where did this issue originate from, did you just decide JS should have this problem and therefore create it?  I was looking for a similar issue in Ruby but see nothing...

**Comment by SleeplessByte** [comment]
Yep. I manually created an issue per missing exercise.
