### ISSUE TITLE
difference-of-squares: dependencies depreciated - bug

### ISSUE THREAD

**Issue by hannakim91** [exercism/javascript#936]
```
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

I tried to install dependencies for this exercise and ran into these error messages.

Tests will run (and fail) if code run for assertions are left blank and can pass if the return statements of functions are what's expected:

![Screen Shot 2021-01-18 at 3 00 01 PM](https://user-images.githubusercontent.com/62962173/104966322-d8fb0880-599d-11eb-91e7-be99635f60cf.png)

**Comment by SleeplessByte** [comment]
Hi there!

I see you've closed this out. Were you able to figure out what was wrong? Otherwise I can explain to you what happened :)

**Comment by hannakim91** [comment]
Hi Derk-Jan,

Thanks for checking in! I had assumed the error messages I was getting from
running tests was due to the depreciated package warnings I got after
running `npm install` but turns out I had written some bad logic.  😰

I'm still in fairly early stages of learning to code and it's great to know
that you have such an active community checking in on issues!

Best,
Hanna

**Comment by SleeplessByte** [comment]
All good! 

Good luck on your journey :)

P.S., I don't know, without seeing your actual solution, if the code had bad logic -- it was 'just' not efficient enough, trying to allocate over 1GB of memory ;). That exercise has, purposefully, test case(s) to trigger this type of situation, so a brute-force/naïve solution won't pass all the tests.

**Comment by hannakim91** [comment]
Thank you for the well-wishes.

Seems you have a good nose for these things - I ended up solving the
problem using an IDE instead. It made me realize I'd created an infinite
loop when I was running the Exercism test. I'll be sure to 'google' any
unfamiliar error messages first next time!

Thanks for your hard work!

Best,
Hanna
