### ISSUE TITLE
[V3] Update implementing-a-concept-exercise.md

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/javascript#950]
[javascript/reference/implementing-a-concept-exercise.md](https://github.com/exercism/v3/blob/master/languages/javascript/reference/implementing-a-concept-exercise.md) is outdated. It still has the `after.md` file, and lacking the details on `<concept>.md` and `approaches.md`.

Follow https://github.com/exercism/v3/issues/2592 once it's done/documented.

**Comment by junedev** [comment]
Closing this because it was already addressed.
